### ISSUE TITLE
[10.0] Bug on contract_template_id onchange in module contract

### ISSUE THREAD

**Issue by hurrinico** [OCA/contract#100]
Step to reproduce:
-create a contract
-flag recurring_invoices and add a contract_template_id (must have at least a line)
      - the onchange works and you can see the line
-Save, the field recurring_invoice_line_ids it's empty
Imho [this](https://github.com/OCA/contract/blob/10.0/contract/models/account_analytic_account.py#L46) doesn't work well with one2many fields.
@pedrobaeza @carlosdauden any idea?

**Comment by pedrobaeza** [comment]
See https://github.com/OCA/contract/pull/92
