### ISSUE TITLE
Error when selected auto renew in contract template

### ISSUE THREAD

**Issue by RicRodS** [OCA/contract#1025]
## Module
contract

## Describe the bug
I create a contract template with auto renew checked. When I select this template in the contract throw this error: 
```
Missing Record
Record does not exist or has been deleted.
(Record: contract.contract(7,), User: 2)
```

## To Reproduce
**Affected versions**:
Odoo 16.0-20231115 on a bitnami package for AWS

1. Create a new template with auto-renew cheked
2. Create a new contract and select the template
3. Enjoy the error

**Comment by flotho** [comment]
did you try recently on runboat ?

**Comment by RicRodS** [comment]
I haven't try the lastest versión, i did a workaround

**Comment by TxTechnician** [comment]
Ive gotten the same problem on two fresh installs.  The problem is intermittent.  I am using Version 18.

<img width="1609" height="654" alt="Image" src="https://github.com/user-attachments/assets/63f59b8d-e404-45b4-910d-c2437b2dab77" />
