### ISSUE TITLE
Invoice lines are not assigned with the correct partner_id

### ISSUE THREAD

**Issue by decentlab** [OCA/contract#1030]
## Module
contract

## Describe the bug
Some of the invoice lines generated by the contract module are assigned with a wrong partner. However, the invoice itself is assigned with the correct partner. This causes the payment being registered to a wrong partner.

## To Reproduce
**Affected versions**: 16.0.2.0.0

1. Generate invoice via contract with multiple lines
2. Register payment on the generated invoice

**Expected behavior**
The registered payment partner must match the invoice partner.

**Additional context**

`Recurrence at line level` is enabled.

This bug is not visible on odoo 15. So perhaps starting from odoo 16, the payment partner is taken from the invoice lines instead of the invoice itself. The following patch seems to be a workaround:

```
--- a/contract/models/contract.py
+++ b/contract/models/contract.py
@@ -561,6 +561,7 @@ class ContractContract(models.Model):
             for line in contract_lines:
                 invoice_line_vals = line._prepare_invoice_line()
                 if invoice_line_vals:
+                    invoice_line_vals['partner_id'] = contract.partner_id.id
                     # Allow extension modules to return an empty dictionary for
                     # nullifying line. We should then cleanup certain values.
                     if "company_id" in invoice_line_vals:
```

**Comment by flotho** [comment]
Hi @decentlab 
thanks for the reporting,
any chance to propose a PR ?

**Comment by decentlab** [comment]
Meanwhile, can't reproduce it anymore. Will reopen it when encountered again and trace the exact problem. Thanks.
