### ISSUE TITLE
Question regarding subscription and contract modules

### ISSUE THREAD

**Issue by flotho** [OCA/contract#1040]
Hi everyone,

I can see that subcription module is now part of the OCA repo.
I'm wondering if there is any ducplicate usage wuth contract module ?
What are the use case that will lead us to choose subscription instead of contract ?

Regards

**Comment by rousseldenis** [comment]
That's indeed a good question as functionally, it is quite equivalent...

@carlos-domatix @simahawk @francesco-ooops

**Comment by francesco-ooops** [comment]
I have only followed development and haven't done a full functional analysis myself, but for what I understand contract modules somehow have reached a complexity level where it was difficult to easily attend customer's requests (you can find many comments on the tone of https://github.com/OCA/contract/pull/971#issuecomment-1652404292)

Just consider this repo has approx the same number of issues of huge repos like sale or purchase-workflow...

**Comment by chrisandrewmann** [comment]
I agree that subscription_oca seems much more "lightweight" and has less of a chain of dependencies to maintain.
It's also capable of more common use cases such as generating a sales order or invoice, as well as subscribable products.
I think what would make the real icing on the cake would be to add automatic payments option and also a simple area in the user portal to reflect their subscriptions allowing customers to cancel them.

**Comment by flotho** [comment]
AFAICR, subscription seems to be the future of OCA/Contract repo

**Comment by flotho** [comment]
for the record : https://github.com/OCA/contract/pull/1029

**Comment by flotho** [comment]
actually here is the reasons : https://github.com/OCA/contract/issues/1108
