### ISSUE TITLE
[16.0] Problem with post-period contracts

### ISSUE THREAD

**Issue by flalexg** [OCA/contract#1063]
**Is your feature request related to a problem?**
Hello! I've been investigating a little the code and I think there's an error in the concept of the pre-paid and post-paid terms, specific in the post-paid term.(or maybe I'm who is wrong :P). I'm going to expose the case:

1. I create a Post-Paid contract at 1st January (Monday), with a recurrence of every week. I expect the 'Date of Next Invoice' to be set a 7h January (Sun). But is set on 8th January (Monday).
![Recurrence-Week](https://github.com/OCA/contract/assets/126599115/25b4ac45-e91b-41a9-8e59-6d6c15c0148f)

For me this isn't correct. Explaining in period terms, the periods for this contract are:
* First period: From 1st Jan to 7th Jan
* Second period: From 8th Jan to 14th Jan
* Third period: From 15th Jan to 21st Jan.

Establishing a post-period 'Invoicing Type' means that we generate the contract at the end of the current period (no at the begging of the next one).

If we look on the pre-period 'Invoicing Type', it computes correctly the Date of Next Invoice, setting it at 1st of January in the first period and 8th of January on the second period.
 
![Recurrence-Pre-Paid-Week-0](https://github.com/OCA/contract/assets/126599115/ba31db85-d05e-4d96-b094-2c1d23d35525)
![Recurrence-Pre-Paid-Week-1](https://github.com/OCA/contract/assets/126599115/f505658f-ad7b-4eab-bb55-c2933bb3fcae)

**Describe the solution you'd like**
It's for this that I'm proposing to delete the field 'recurring_invoicing_offset', which is the cause of the error because it established an offset of 1 when it's a post-paid contract. In the new versions it's all controlled with the fields of 'recurring_next_date' and 'last_date_invoiced'.

This change would have a big impact not only for the people who are using this, but for us because we would have to refactor all the test.

I didn't go ahead with the change because maybe I'm the one who is wrong.

**Comment by pedrobaeza** [comment]
It can't be invoiced on the last day of the previous period, because that day hasn't lasted yet, and thus, there can be concepts to be invoiced that are not invoiced. Think that thanks to modules like `contract_variable_qty` or `contract_sale_invoicing`, the idea is to gather, once the period has lasted, all the applicable concepts. You can't do this while the period is still there. For your use case, you want to be invoiced the last day of the period, but that goes against what post-period was created for.

**Comment by flalexg** [comment]
That makes sense. Thank you for the response @pedrobaeza. :)
