### ISSUE TITLE
Delete / archive / empty this repository

### ISSUE THREAD

**Issue by yvaucher** [OCA/contract#11]
All modules of this repository have been moved to https://github.com/OCA/project-service
Don't we want to remove this?

cc @jgrandguillaume @elicoidal @StefanRijnhart @max3903 @nhomar @sebastienbeau @gurneyalex

**Comment by dreispt** [comment]
I can remove all files from master and have the README warning in larger letters.

**Comment by dreispt** [comment]
See PR #12
