### ISSUE TITLE
[17.0] New module: subscription_oca_purchase

### ISSUE THREAD

**Issue by Tisho99** [OCA/contract#1107]
Hi, I am planning to create a new module for subscriptions: subscription_oca_purchase.

The module will inherit subscription_oca and do the same for purchases. A subscription_type field will be added to subscriptions and subscriotion templates to make the logic.

Also, a little refactor to the subscription_oca will be needed. I have considered the following changes:
- Adding the subscription_type field with only the "sale" value.
- Set required=False in the pricelist field of the subscriptions, and adapt to the change all the functions related to pricelists of the subscription and subscription lines models.

Is anyone interested? 

Does anyone see any problems with refactoring oca_subscription?

Other thoughts on this?

**Comment by HaraldPanten** [comment]
@Tisho99 I think you can close this issue. Maybe it's better to continue in this one --> https://github.com/OCA/contract/issues/1108
