### ISSUE TITLE
[16.0] Wrong translation

### ISSUE THREAD

**Issue by jctrey** [OCA/contract#1117]
https://github.com/OCA/contract/blob/93830e41078a60f538bfcf58d9f970885c0598a7/contract/i18n/es.po#L223

The correct translation should be:
```
msgstr ""
"<strong>#END#</strong>\n"
"                                    : Fecha\n"
"                                    fin\n"
"                                    del\n"
"                                    periodo facturado"

```

**Comment by pedrobaeza** [comment]
Please correct it through Weblate:

https://odoo-community.org/page/translate

**Comment by pedrobaeza** [comment]
I have translated it for you this time. Please incorporate the workflow about translations on your company.
