### ISSUE TITLE
[16][IMP] Contract: Smart Button "Contracts" not displayed on Contact until an invoice is published

### ISSUE THREAD

**Issue by fcvalgar** [OCA/contract#1143]
Module
contract

### Describe the bug

The "Contracts" smart button on the contact form view does not appear when a contract is created and in progress. It only becomes visible after an associated invoice is published.

### To Reproduce
Affected versions: Odoo 16

- Create a contract for a contact.
- Set the contract to "in progress" status.
- Go to the contact's form view to check for the "Contracts" smart button.

### Expected behavior:

- [ ] The "Contracts" smart button should be displayed on the contact form as soon as there is an active contract, regardless of whether there is a published invoice.

Additional context This issue limits the ability to view ongoing contracts directly from the contact form unless an invoice has been published.

MT-7885 @moduon

**Comment by rafaelbn** [comment]
Hello @OCA/project-service-maintainers !

Do you agree in this improvement? 😄 

Let me know please! ❤️ 

Thank you!

**Comment by rousseldenis** [comment]
@rafaelbn This is due to :

![image](https://github.com/user-attachments/assets/6f2a2ab0-b311-4d2c-8303-6dc7d0ae90c8)


So the `customer_rank`should be updated when we create a contract IMHO (that's logical). But IMHO too, we should not rely on customer rank to display the smart button.

**Comment by rafaelbn** [comment]
Thank you for answering @rousseldenis !

> But IMHO too, we should not rely on customer rank to display the smart button.

**Comment by fcvalgar** [comment]
To avoid relying on the customer_rank field for the visibility of the smart button, we propose modifying its logic to directly use the contract model.

We can implement a method to check for active contracts associated with the customer. 

> @rafaelbn This is due to :
> 
> ![image](https://private-user-images.githubusercontent.com/19529533/386096293-6f2a2ab0-b311-4d2c-8303-6dc7d0ae90c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwOTEzNTMsIm5iZiI6MTczMjA5MTA1MywicGF0aCI6Ii8xOTUyOTUzMy8zODYwOTYyOTMtNmYyYTJhYjAtYjMxMS00ZDJjLTgzMDMtNmRjN2QwYWU5MGM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDA4MjQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkOWQxYmI5NmQ0MTdhYzg2NDk3MjU0NzJlZjdkNWZjNjQzYzJjNjU2ZjgwMTZmMDgxMDYxYmY1MjIzYmM2MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WgOMf3Ew0OChryEx7R8UFKAsynkqqWMr9L2ty6HC7ss)
> 
> So the `customer_rank`should be updated when we create a contract IMHO (that's logical). But IMHO too, we should not rely on customer rank to display the smart button.

**Comment by carlosdauden** [comment]
When creating a customer from, for example, Invoicing > Customers the customer created is already assigned a customer_rank value, so I don't understand the problem with the current behaviour.

https://github.com/odoo/odoo/blob/62af1c7b04557e94d18d6078544dc867e61ef2d2/addons/account/views/partner_view.xml#L280

**Comment by fcvalgar** [comment]
In our use case, we use the Members module, and contacts are created from this module. Thank you for the feedback!  @carlosdauden 

> When creating a customer from, for example, Invoicing > Customers the customer created is already assigned a customer_rank value, so I don't understand the problem with the current behaviour.
> 
> https://github.com/odoo/odoo/blob/62af1c7b04557e94d18d6078544dc867e61ef2d2/addons/account/views/partner_view.xml#L280

**Comment by carlosdauden** [comment]
You can add that context in Members module

**Comment by fcvalgar** [comment]
> You can add that context in Members module

It may happen that one of the previous contacts in our database is the owner of a contract. Until that contract has a posted invoice, the smart button will not be visible.

The OCA Subscriptions module follows the same logic.

[https://github.com/OCA/contract/tree/16.0/subscription_oca

(https://github.com/OCA/contract/blob/16.0/subscription_oca/views/res_partner_views.xml)

![image](https://github.com/user-attachments/assets/f67f7921-4042-446f-90e8-3afca5bc77a4)

**Comment by carlosdauden** [comment]
You always can add a action server (or script) to improve your database data. :wink:

**Comment by carlosdauden** [comment]
You can close, resolved here https://github.com/OCA/contract/pull/1152

**Comment by rafaelbn** [comment]
Solved in https://github.com/OCA/contract/pull/1152
