### ISSUE TITLE
create invoices before the date invoice

### ISSUE THREAD

**Issue by cesarsc79** [OCA/contract#126]
For example:

the 25th November, i want to create some invoices but with date of invoice  1th December

How i can do it?

**Comment by carlosdauden** [comment]
Three options:
 - You can click Create invoice link in a contract form showing debug options
 - You can create an action to call recurring_create_invoice()
 - You can call contracts.recurring_create_invoice() in a new cron.

**Comment by peter2018abc** [comment]
> Three options:
> 
>     * You can click Create invoice link in a contract form showing debug options
>     * You can create an action to call recurring_create_invoice() 
>     * You can call contracts.recurring_create_invoice() in a new cron.

I tried to add an action in order for my users to be able to manually create the next invoice, but it's not working (nothing happens).

What I did:
In gui I created a new server action like this:
![grafik](https://user-images.githubusercontent.com/46168043/51380412-02b09900-1b12-11e9-9698-10e047b1a71a.png)


Unfortunately it's not working...
