### ISSUE TITLE
[RFC] contract_company_users: Bill for companies & users

### ISSUE THREAD

**Issue by lasley** [OCA/contract#131]
This module will provide the ability to create a contract that provides access into the current Odoo system. A user would purchase this contract for $X/user/$Interval, which would subsequently:
* Create a company in Odoo related to the contract
* Add the user to the new company
* Give the user the ability manage permissions for their company
* Provide different pricing for users dependent on their security permissions + a base price

The obvious challenge here is how to isolate the company selling the contract from the company purchasing it, while still allow the users to manage everything within their own company. My limited testing on this points me to believe that by assigning the master company as the parent of the new ones, things just seem to work.

To that end, following are my current specs. Would be interested to hear if anyone has thoughts on this plan - particularly if some other modules may assist me here somehow. The naming sucks too, so suggestions there would be awesome.

1. It should provide the ability to relate products to user security groups
    1. It should hide a select set of groups that would be deemed harmful to the system (such as the ability to install applications, create server actions, etc)
1. It should relate all users back to their contract, if there is one
1. It should automatically determine invoice lines based on the amount of users matching the security group defined in the product related to the each contract line
1. It should override the user creation view for any user that is related to a contract
    1. It should only allow for the selection of security groups named in the contract
    1. It should not allow any multi company options
1. It should automatically create a proration invoice when a new user is created for a company
    1. It should automatically validate and bill against the contract's defined payment method
    1. It should add the correct product to the proration invoice by matching against the contract line product security group definitions
        1. If the new user does not match a contract line, an invoice should not be created
1. It should allow for prices to be customized per subscription contract

**Comment by pedrobaeza** [comment]
Closing as the original issuer is not here anymore.
