### ISSUE TITLE
[Functional Improvement] Recurring Next Date Scoope

### ISSUE THREAD

**Issue by angelmoya** [OCA/contract#137]
The cron function witch create recurring invoices is:

```
    @api.model
    def cron_recurring_create_invoice(self):
        today = fields.Date.today()
        contracts = self.with_context(cron=True).search([
            ('recurring_invoices', '=', True),
            ('recurring_next_date', '<=', today),
            '|',
            ('date_end', '=', False),
            ('date_end', '>=', today),
        ])
        return contracts.recurring_create_invoice()
```

That create invoices only if ('recurring_next_date', '<=', today)

what do you think about create invoices X days before, for example:
```
scoope_day = today + timedelta(X)
...
('recurring_next_date', '<=', scoope_day)
```

**Comment by pedrobaeza** [comment]
Well, it can be good if it's set as a parameter. Can be done at journal level, company level or system parameter. The second one can be the best balanced maybe.

**Comment by angelmoya** [comment]
Yes, I was thinking about create X as a system parameter.

**Comment by angelmoya** [comment]
Yes, I was thinking about create X as a system parameter.

**Comment by pedrobaeza** [comment]
Better by company...

**Comment by cesarsc79** [comment]
[contract_days_before.zip](https://github.com/OCA/contract/files/1714409/contract_days_before.zip)

Sorry:

I am development a new module (not finished yet... NO TIME )
it create 2 field

1º Days before
2º Virtual date

Virtual date is the today.date + Days before
    
So, you can custom every contract separately

 antelacion = fields.Integer(
        string='Dias de antelacion',
        default=5,
        help="Mete los dias de antelacion con los que quieres ejecutar el cron",
    )

virtual_date = fields.Date(
        string='Fecha Virtual',
        compute='_compute_date'
    )

    def _compute_date(self):
        self.virtual_date = date.today() + timedelta(days=self.antelacion)

    @api.model
    def cron_recurring_create_invoice(self):

        contracts = self.with_context(cron=True).search([
            ('recurring_invoices', '=', True),
            ('recurring_next_date', '<=', **virtual_date**),
            '|',
            ('date_end', '=', False),
            ('date_end', '>=', today),
        ])
        return contracts.recurring_create_invoice()

well .... dont work... i am not an an expert in odoo orm

someone wants finish it??

p.d.
other option is add an action in contract form list, for select all contract you want and execute the cron manually without need to go into form view...

**Comment by babatoko** [comment]
This feature will be highly appreciate.

**Comment by NL66278** [comment]
@angelmoya @babatoko If you could test/review my PR it would be appreciated. If PR is accepted, i will also forward port it to 11.0 and 12.0.

**Comment by rafaelbn** [comment]
I close this issue as it has been done in https://github.com/OCA/contract/pull/282
