### ISSUE TITLE
[V11] contract invoicing user

### ISSUE THREAD

**Issue by levkar** [OCA/contract#157]
Invoicing user can see contracts menu, see contracts list but getting access error to account.analytic.invoice.line.

A user needs "Full accounting features" to use contracts, so it's better invoicing users not to see the contracts menu.

**Comment by pedrobaeza** [comment]
Or give read permission to that model...

Can you please make the proper PR?

**Comment by levkar** [comment]
Here's the PR.
https://github.com/OCA/contract/pull/159

I think having seperate access groups would be better in the long run. (i.e. contract manager, contract user) which would also make contract_sale module obselete.
