### ISSUE TITLE
Last day of month

### ISSUE THREAD

**Issue by babatoko** [OCA/contract#161]
How can generate invoice with always the last day of the month.

Actually, if the previous month was a 30 days-month, the next month will be regenerate on 30 of the month instead of 31 of the month. 

Maybe I do miss somethings

**Comment by pedrobaeza** [comment]
Yeah, this is a not yet covered option in the module I'm afraid.

**Comment by carlosdauden** [comment]
v9.0:
https://github.com/OCA/contract/blob/cb8d77a25172c8bd306c005cbfbaee9d5ec2e983/contract/models/contract.py#L120

v10.0:
https://github.com/OCA/contract/blob/739330182c708bb4ad0fa39ae910501110ee5ed6/contract/models/account_analytic_contract.py#L43

v11.0:
https://github.com/OCA/contract/blob/2a8d2bad2f278934fca3e4f11692d11d712e2b08/contract/models/account_analytic_contract.py#L43

**Comment by pedrobaeza** [comment]
Right, I didn't remember that the feature was added!

**Comment by babatoko** [comment]
Yes I've se en that point but it doesn't do the trick. It doesn't influence
the next invoice date field as shows my test.

Regards

**Comment by pedrobaeza** [comment]
Try on runbot and give detailed steps to reproduce the error.
