### ISSUE TITLE
[contract_payment_auto] Lack of robustness - missing commits after each payment (?)

### ISSUE THREAD

**Issue by fcayre** [OCA/contract#166]
Hi folks,

I recently faced an important issue (see https://github.com/OCA/contract/issues/165) which rolled back the creation of a bunch of payment transactions in odoo, while their acquirer counterpart operations were sent to the bank. At next cron execution time, all these operations were then re-executed, resulting in a double bank payment.

The consequences would have been mitigated if a commit had been executed in the recurring task loop. Do you agree? Where in the code would you put that commit? In `AccountAnalyticAccount.recurring_create_invoice` in contract/models/account_analytic_account.py? Any advice before I give it a try and submit a pull request?

**Comment by pedrobaeza** [comment]
No, that's not a good technique. You should never commit inside a transaction, or you can have an inconsistent situation.

**Comment by fcayre** [comment]
Hello @pedrobaeza thanks for your answer. However, present issue describes a problem (global rollback of operations that are independent by nature) which is not solved, so I don't think it should be closed so fast as there is room for improvement here.

The `AccountAnalyticAccount.cron_recurring_create_invoice` method from contract/models/account_analytic_account.py might be the right place to use the `api.Environment.manage` context manager mentioned in https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#never-commit-the-transaction to create isolated valid transactions (one for each contract).

What do you think?

**Comment by pedrobaeza** [comment]
@nhomar why do you reopen? You know that there should never be a commit in the middle of the operation.

**Comment by pedrobaeza** [comment]
Closing as there's an opened PR about this and being discussed there.
