### ISSUE TITLE
[11.0] Help pls: Contract Variable Qty Timesheet

### ISSUE THREAD

**Issue by ghost** [OCA/contract#176]
Hello,

how is to use this module?

Which project (or task) timesheet is to use for the hours. I dont understood the relation between project <-> contract.

Thx!

**Comment by pedrobaeza** [comment]
This issue tracker is not for solving dudes. Please ask on lists or forums. But here is a quick tip: project has an analytic account, and this analytic account can be a contract if you mark the recurring invoicing flag.
