### ISSUE TITLE
Error installing module  ¨contract_payment_mode¨

### ISSUE THREAD

**Issue by thiago95macedo** [OCA/contract#180]
v11.0 - Error installing module
 ¨contract_payment_mode¨
_________________________
The operation can not be completed, probably due to the following factors:
- deletion: you may be trying to delete a record while other records still refer to it
- creation / update: a required field is not configured correctly

[object with reference: Payment methods - account.payment.mode]
_________________________

**Comment by pedrobaeza** [comment]
The module is working correctly on runbot (https://runbot.odoo-community.org/runbot/repo/github-com-oca-contract-110), so something bad should be in your DB. Can you put the server stack trace?

**Comment by thiago95macedo** [comment]
I persisted that in a clean installation the module installs perfectly, however, when I install on a base that already has some mode of payment configured it presents this error.

**Comment by pedrobaeza** [comment]
Do you have multi-company? You haven't still put the stack trace I asked you.

**Comment by thiago95macedo** [comment]
I do not use multi-companies.
Regarding the stack trace, I'll do it, I apologize. I'll see how it's done because I've never done the procedure before.
