### ISSUE TITLE
Issue: Partner warning (block message) on invoice

### ISSUE THREAD

**Issue by angelmoya** [OCA/contract#182]
On partner form you can set "Warning on invoices" as "Blocking message".

If this partner has contract with "Generate recurring invoices automatically" then the Scheduled Action "Generate Recurring Invoices from Contracts" will fails because is not able to create invoice without partner.

There is right to don't create this invoice, invoice could not be created, but all process fails and no one invoice is created from the other contracts.

I think we need to prevent set "Warning on invoices" as "Blocking message" is there are any contract on this partner, maybe with a constraint. And also show same warning mesage for invoices on contracts.

**Comment by pedrobaeza** [comment]
We can mask each invoice creation for not stopping full loop and post a message on contract chatter (do we have one on analytic account?) if fails.

**Comment by pedrobaeza** [comment]
@angelmoya are you going finally to perform this?
