### ISSUE TITLE
Partner delivery address in contracts

### ISSUE THREAD

**Issue by xabispacebiker** [OCA/contract#191]
When creating invoices from contracts, the delivery address is not filled in the generated invoices. I am trying to modify this behaviour by adding the following code in contract/models/account_analytic_account.py without success:

```
214     @api.multi
215     def _prepare_invoice(self):
.....
239             'partner_shipping_id': self.partner_id.address_get(
240                 ['delivery'])['delivery'],
```
What should be modified in order for the invoice to catch the partner_id's partner_shipping_id?

Thanks in advance

**Comment by xabispacebiker** [comment]
I am not looking for someone to write me the code, just some advice. Anyone ?

**Comment by pedrobaeza** [comment]
Try `self.partner_id.commercial_partner_id.address_get...`

**Comment by xabispacebiker** [comment]
Hi Pedro, thanks for your answer. I am not really sure that will work, as for testing purposes I added a fixed value, which was a valid partner_shipping_id, and nothing happened. So even if `self.partner_id.commercial_partner_id.address_get` returns a valid value I think there is something else to be done.

**Comment by pedrobaeza** [comment]
Then it's changed in other place. Check calls to onchange methods.

**Comment by pedrobaeza** [comment]
Closing as no more answer.
