### ISSUE TITLE
[10.0][BUG] contract_sale_generation - cron tasks always change 'recurring_next_date'

### ISSUE THREAD

**Issue by Bilbonet** [OCA/contract#193]
This module create a new cron task for contracts configured for "sale orders".

The problem is that this cron task change 'recurring_next_date' of the contracts configured for "sale invoices".

And the cron task for invoices change 'recurring_next_date' of the contracts configured for 'sale orders.'

**Comment by pedrobaeza** [comment]
@angelmoya can you check?

**Comment by pedrobaeza** [comment]
Triaging this as outdated version.
