### ISSUE TITLE
Prorated invoicing of contracts

### ISSUE THREAD

**Issue by gva-acsone** [OCA/contract#197]
Hi,

I am currently encountering the following use case that I can't (or don't know how to) solve with the current modules. Any ideas on how to deal with this use case or any opinion on the proposed new feature?

First, I would like to invoice my contracts on the last day of each month (recurring_interval set to 'Month(s) last day'). 
But, I would like to invoice my contract based on a pro rata percentage if the contract didn't start / end on the first/ respectively last day of a month. So I would like to calculate the amount I charge to my customer based on the amount of days the contract was effectively active during the month. With the current module, a full fee is for example charged to the customer at the end of February, even though the contract only started on the 24th of February. I would like to charge my customer for only 5 days (from the 24th to the 28th of February), not for a full month.

In our opinion, the following feature/module should be added:

- Adding a 'prorated invoicing' checkbox on a contract template and on the contract lines. 
- This box can only be checked when the 'recurring interval field' is set to 'Month(s) last day'
- The 'prorated invoicing' checkbox on the contract line is automatically filled with the information coming from the contract template, but can be modified manually by the user on each contract line.

If this checkbox is checked, Odoo will apply a special 'pro rata rule' to calculate the amount to add on the invoice for the first and the last month of the contract (only!). The other months of the contract are invoiced normally (full amount). 

One of the two following options should be chosen to calculate the pro rata percentage (that should be multiplied with the full amount to calculate the amount that will be charged to the customer for its first month of contract):
1.  Amount of days the contract was active (during the first month) divided by the amount of days we have in the month. So if the contract starts on the 24th of February, the pro rata percentage when the bill will be generated (on the 28th of February) will be (5/28 = 17,86%). So only 17,86% of the total amount will be charged to the customer for February.
2. Amount of days the contract was active (during the first month) divided by a fixed amount of days (independently of the amount of days we have in the month). I divided 365 by 12 to obtain a plausible amount (= 30,42). Hence, for my example, we would have (5/30,42=16,44 %), so 16,44% of the total amount will be charged to the customer for February. This second method is easier as it doesn't take the amount of days of the month into account.

For the last month of the contract, we could either apply one of these 2 rules (the same as the one we chose for the first month) to calculate the pro rata percentage or we could decide to take the residual amount that was not charged to the customer on the first month and charge this amount to the customer on the last month (only if contracts cannot be cancelled before a full amount of months has been reached). 

Any ideas / opinion on this?

Thanks

**Comment by gva-acsone** [comment]
@sbidoul @sbejaoui

**Comment by pedrobaeza** [comment]
You can and should do this with `contract_variable_qty` + a formula that you can call it "Prorated quantity" that computes the part of the quantity to invoice. Ask your technical colleagues for programming that formula, which is not very difficult.

**Comment by rafaelbn** [comment]
Hi @gva-acsone ,

> First, I would like to invoice my contracts on the last day of each month (recurring_interval set to 'Month(s) last day').

You can use also ` Invoicing type ` = `post-paid`

> But, I would like to invoice my contract based on a pro rata percentage if the contract didn't start / end on the first/ respectively last day of a month

We solved this situation in the case of associations with:
- https://github.com/OCA/vertical-association/tree/11.0/membership_prorate

It is not you case of course, just to note that we create recurring contracts with the **product** which is a membership product and the product has this prorrated checkt

What I mean is that don't do it in contract level but in contract line level. Because a more general case is that one line you don't want prorrate and another yes

**Comment by gva-acsone** [comment]
Working with the contract_variable_quantity to deal with this case looks like an easy solution! 
We will work on this formula and add it in the OCA module.

Thanks!

**Comment by pedrobaeza** [comment]
Yes, the formula should read contract start date and invoicing start and end period for computing the proportional (or full) part. Closing this issue then.

**Comment by gva-acsone** [comment]
Can you re-open the issue and set it as 'enhancement' as we plan to implement it as an OCA-module?

**Comment by pedrobaeza** [comment]
OK, reopening then. I suppose you will do something similar to https://github.com/OCA/contract/tree/11.0/contract_variable_qty_timesheet, but for prorated.

**Comment by pedrobaeza** [comment]
Any news about this?

**Comment by pedrobaeza** [comment]
Closing as there's a linked PR.
