### ISSUE TITLE
Update of 'Date of next invoice' when the recurring_interval is set to 'Month(s) last day'

### ISSUE THREAD

**Issue by gva-acsone** [OCA/contract#198]
Hi,

I observe that the 'date of next invoice (recurring_next_date) is not automatically updated when the 'Recurring_interval' (='Repeat every' field) is set to 'Month(s) last day'. For example, we have a 'start date' on the 25th of October and I decide to apply a 'Recurring _interval' of ' 1 Month(s) last day'. My 'date of next invoice' will not be changed by Odoo, so it will still be set on the 25th of October.

Hence, the first invoice will  be generated on the 25th of October by Odoo, and not on the 31st of October as I would expect. After the first invoice has been generated, the 'Date of Next invoice' will be automatically adapted by Odoo to take the 'Recurring interval' into account. So the second invoice will be correct (on the 30th of November and not on the 25th of November). 

According to me, the'Date of Next invoice' should be set automatically by Odoo on the last day of the month once the 'Recurring_interval' is modified by the user and set on 'Month(s) last day'. This ensures that the first bill will be created on the correct date (last day of the month).  If needed, this 'Date of next invoice' can always be modified manually by the user. 

What do you think about this?

Thanks!

**Comment by rafaelbn** [comment]
Hi @gva-acsone IMHO,

` Date of Next Invoice ` should be set manually when you create de contract so the problem disappears. But you proposal in not bad in fact in an improvement

**Comment by pedrobaeza** [comment]
Yeah, it would be a good improvement, but only applies to that specific option. The rest of possible recurrences shouldn't modify it.

**Comment by gva-acsone** [comment]
Thanks for the feedback ! 
@rafaelbn, could you please change the label to 'Enhancement' ?
@sbejaoui will implement this in the following weeks.

Thanks
