### ISSUE TITLE
[10.0] date_format should be defaulted to company's locale

### ISSUE THREAD

**Issue by matteotrubini** [OCA/contract#199]
https://github.com/OCA/contract/blob/99b130023154e6e8fb0ff0bb403282c33bffbeca/contract/models/account_analytic_account.py#L203

In this way if the company has '%d/%m/%Y' format, but the parnter has no language, dated are formatted '%m/%d/%Y'

**Comment by pedrobaeza** [comment]
OK, it's something acceptable. Please make the PR changing that.

**Comment by matteotrubini** [comment]
I'm sorry, I'm not a python developer, I only checked the code to understand a "strange" behavior :(

**Comment by pedrobaeza** [comment]
Then we let this opened to be aware of this and for anyone who wants to change it.
