### ISSUE TITLE
Invoicing 'one-shot costs' on contracts

### ISSUE THREAD

**Issue by gva-acsone** [OCA/contract#201]
Hello,

**Problem:**
Besides 'activation costs' related to a contract (invoiced at the end of the order month), users should also be able to charge 'one-shot costs'. These costs are invoiced at the end of the month where the contract officially starts (contract start date), which doesn't necessarily correspond to the month during which the order takes place. These one-shot costs are of course only charged once. 

In the OCA module, a new contract line can be added below the main contract line. Once the first invoice is generated for this contract, the quantity for this line can be set to zero. However, this requires a manual action by a user, which will often lead to mistakes. Activities could be used to avoid oversights, but an easier solution should be invented.

Do you know an easier way to deal with this problem in the core OCA module?

**Solution:**
To ease the treatment of one-shot costs, we could:
1° Add a flag 'One-shot cost' on the product form and on the contract line
2° If checked, this contract line is only invoiced once. 
--> 2 solutions: The invoicing mechanism is adapted to 'avoid' invoicing twice the same one-shot cost
OR
Once the first invoice has been generated, the quantity on the 'One-shot cost' line is automatically set to 0 by Odoo. 

What do you think about this? Anyone already working on such a functionality? 

Thanks for your feedback

**Comment by gva-acsone** [comment]
@sbidoul @sbejaoui

**Comment by rafaelbn** [comment]
Hi @gva-acsone ,

You can do it with https://github.com/OCA/contract/tree/11.0/contract_sale_invoicing
+
You have to make a sale order and set the AA of the SO which must be the same as the contact

By the way take a look in:

- https://github.com/OCA/contract/tree/11.0/contract_variable_quantity
- https://github.com/OCA/contract/tree/11.0/contract_variable_qty_timesheet

The only flow I miss in contract is to create a contract from a SO... :cry: because this BUG https://github.com/OCA/contract/issues/138

cc @carlosdauden  @sergio-teruel

**Comment by pedrobaeza** [comment]
There are 2 possible paths:

- The same as #200, using starting/ending dates.
- As my colleague says, using an SO with that one-shot costs, that can be invoiced with contract_sale_invoicing. In fact, this can be the usual flow: you first quote the contract with a product that will be the recurring one (with module `product_contract`, which is currently broken in v10 and not migrated to v11), and other that are one-shot. Confirming the quote, you have the contract, and with the other module, you invoice at the same time the other products.

**Comment by gva-acsone** [comment]
Thanks for the solution !
