### ISSUE TITLE
Improve the contract creation from a Sales Order

### ISSUE THREAD

**Issue by gva-acsone** [OCA/contract#205]
Hello,

When validating a SO that contains a 'Contract product', a new contract is created in Odoo. This new contract is related to the contract template mentioned on the 'contract product form' and contains all the invoice lines (quantity + product + price + discount) mentioned on this contract template. The 'contract product', quantity, discount and price mentioned on the SO lines are not copied on the contract. Hence, if a discount, special price or multiple quantity is mentioned on the SO, it is not taken into account on the contract. 

Wouldn't it be interesting to allow users to decide that the 'contract products' mentioned on the SO are added on the contract? And that we only take the other parameters (invoicing type, journal, contract type, repeat every...) from the contract template?

Did I miss something in the OCA modules that allows the user to do this?

Based on the new behavior for contracts described by @sbejaoui on issue #200 (adding start/end dates and the invoicing recurrency on the contract lines instead of the contract form) , we would propose the following enhancement:

1. The Sales Order Lines that are related to 'Contract products' are added on the contract(s) created from the Sales Order. So we take all the informations (product, description, quantity, unit price, discount ...) from the SO lines that are linked to 'contract products' and add them on the contract lines. All invoice lines on the contract template related to a contract product are also added on the contract created based on the SO. So we take the invoice lines on the contract template, as well as the SO lines that contain contract products (while we only took the invoice lines of the contract template before) . This allows users to insert mandatory costs on the contract template and add them on the contract with the contract products selected on the Sales Order.

2. We add 'Contract start and end dates' on the SO lines for products that are flagged as contracts. These start and end dates are copied on the contract lines created from the SO. The invoicing recurrence is also added on the SO lines for contract products. This invoicing recurrence is automatically filled in with the recurrence mentioned on the product form (new mandatory field). This information can not be added on the contract template as we will otherwise not be able to add products with a different invoicing recurrence on the same contract.

3. A 'contract' field is added on all the sales order lines that contain 'contract products'. This field enables users to add this SO line in an existing contract once the SO is confirmed. Only the active contracts for which the contract template is similar to the one on the product form will be proposed in this field. 
Sales order lines for which the 'contract field' has not been completed lead to the creation of (a) new contract(s) (based on the contract template)

4. The invoicing policy on SO should be modified so that invoices created from a SO don't include contract products.

5. The link between a sale order line and a contract line will be extended to the invoice lines so that invoices created from a contract are related to the initial SO (and visible in the Invoices tab on the SO).

Thanks for your feedback / ideas !

**Comment by pedrobaeza** [comment]
@rafaelbn you know `product_contract` more than me. Can you answer?

**Comment by pedrobaeza** [comment]
We can close this I think, isn't it?

**Comment by gva-acsone** [comment]
Yes, the functionality has already been developed by @sbejaoui in Pull Request  https://github.com/OCA/contract/pull/207
