### ISSUE TITLE
11 contract

### ISSUE THREAD

**Issue by cesarsc79** [OCA/contract#213]
After update, i have 2 menuitem in sale menu
contracts  and customer contracts

and

1 menuitem supplier contract

the issue is that dont work  Scheduled ActionsGenerate/ Recurring Invoices from Contracts

i have to run it manually

**Comment by pedrobaeza** [comment]
Remove the cron and update the module.

**Comment by cesarsc79** [comment]
thank you Pedro.

I´ve done ( Remove the cron and update the module. ) but dont work yet

i have to do it manually

????

**Comment by pedrobaeza** [comment]
Check log for possible errors.
