### ISSUE TITLE
Add relation to cost in the reoccurring invoice

### ISSUE THREAD

**Issue by ntodorova** [OCA/contract#214]
Hi all,
I just wanted to ask if there are some ideas for implementing relation to Purchases in the reoccurring invoice.
Here is the background:
We have a contract and reoccurring invoice. There is already a functionality that connects not invoiced sale orders from the same account. But what about goods purchased from the company, but related to the contract i.e
we have a customer x, we have a contract for support 100h
we have buy for the same customer product y, which is also related to this contract
we want to have the PO related to that contract.
Are there any ideas on the matter?

**Comment by pedrobaeza** [comment]
Not by my part. You can do something similar to `contract_sale_invoicing` I guess, but for purchase part.

**Comment by ntodorova** [comment]
Thank you @pedrobaeza! Lets see if someone else have some ideas here : )))
I was thinking just to add m2m field relation btw. contract and  PO just to be able to filter afterwards for related documents. But this is just a basic solution and does not give the opportunity for an overview of the costs and revenue

**Comment by pedrobaeza** [comment]
Triaging this as old.
