### ISSUE TITLE
agreement_fsm

### ISSUE THREAD

**Issue by max3903** [OCA/contract#224]
Dependencies: fieldservice, agreement
License: AGPL-3

# Module description

Odoo Agreement App does not provide an easy way to access field service orders related to an agreement. Some organizations needs to have a quick access to field service orders to track the performance of an agreement.

This module allows you to link a field service order to an agreement and adds a smart button on the agreement to look at the list of related field service orders.

# Usage

* Go to Field Service > Operations > Orders
* Select or create a field service order and set the agreement
* Go to Agreement > Agreements
* Open the previous agreement
* Click on the smart button "Service Orders" to see the list of related field service orders

# Technical Specifications
* In the agreement module, add a setting option to install agreement_fieldservice
* Add a many2one field "Agreement" (agreement_id) on fsm.order
* Add a smart button on agreement to show the list of related field service orders

**Comment by bodedra** [comment]
@max3903 I am working on these.
