### ISSUE TITLE
Raising errors for missing modules by agreement_fsm (and it is not really installed)

### ISSUE THREAD

**Issue by etobella** [OCA/contract#231]
With agreement_fsm, you must have the repository  https://github.com/asaunier/geospatial.git installed in order to not raise errors. Can you remove somehow this lines of code:

https://github.com/OCA/contract/blob/11.0/agreement_fsm/models/fsm_order.py#L6

**Comment by etobella** [comment]
Also, the dependency that is giving problems is not even in OCA:
https://github.com/OCA/field-service/blob/11.0/oca_dependencies.txt#L17

**Comment by etobella** [comment]
@max3903 @bodedra this is related to your PR

**Comment by pedrobaeza** [comment]
Please never introduce things outside OCA. @max3903 you should double check everything before merging.

**Comment by etobella** [comment]
Also, the added module is specific to field-service, so I think it could be better to add it to field-service. 
Right now, we cannot refresh the modules we use from this repo because it is giving warnings because it is not using the standard inheritance system.
As I am not used to the field-service system, so I don't know the implications of the change.

**Comment by max3903** [comment]
@etobella We will move it to OCA/field-service. Sorry for the inconvenience.
