### ISSUE TITLE
agreement_sale

### ISSUE THREAD

**Issue by max3903** [OCA/contract#234]
Dependencies: sale, agreement
License: AGPL-3

# Module description
Odoo Sales App does not support the management of legal content for agreements and contracts. It's also not integrated with the Agreement App.

This module is for companies that needs their customer to sign an agreement with all the legal information based on the selected agreement template.

# Configuration
* Go to Agreements > Configurations > Templates
* Create a template
* Go to Agreements > Master Data > Sections
* Create sections with content

# Usage
* Go to Sales
* Create or select a quotation
* Set the agreement template and add some products
* Confirm the quotation. An agreement is created and linked to the sales order:
  * the agreement template is copied into an agreement with a copy of the sections, clauses, recitals and appendices
  * all the sales order lines are added as agreement lines
  * the products on the SO with BOM are added as service profile on the agreement
  * the customer information is set from the sales order
  * the eventual analytic account linked to the sales order is set on the agreement
  * the agreement is linked to the sales order and vice versa

# Technical Specifications
## sale.order
- [x] Add a many2one field "Agreement Template" (agreement_template_id) to agreement.template
- [x] Add a readonly many2one field "Agreement" (agreement_id) to agreement

## agreement
- [x] Add a readonly many2one field "Sales Order" (sale_id) to sales order
- [x] When the quotation is confirmed:
  * the agreement template is copied into an agreement with a copy of the sections, clauses, recitals and appendices
  * all the sales order lines are added as agreement lines
  * the products on the SO with BOM are added as service profile on the agreement
  * the customer information is set from the sales order
  * the eventual analytic account linked to the sales order is set on the agreement
  * the agreement is linked to the sales order and vice versa

**Comment by bealdav** [comment]
This module already exist in v10

**Comment by bealdav** [comment]
I'll port it to v12

**Comment by max3903** [comment]
We will do to v11 ;)

**Comment by alexis-via** [comment]
Yes, it's a mess ! @max3903  created a new module agreement_sale in v11 instead of porting the agreement_sale module from v10 and adapting it and make it evolve. So several features of the agreement_sale module of v10 are now broken in upper versions. I'll propose a PR on v12 to reconcile your module agreement_sale of v11 and my module agreement_sale of v10. There 2 scenarios: @max3903 accepts the PR and I can continue to use the agreement* modules. Otherwise, I'll re-create new modules elsewhere.
