### ISSUE TITLE
upgrade from odoo8

### ISSUE THREAD

**Issue by peter2018abc** [OCA/contract#244]
Hi,
I am using account_analytic_analysis in odoo8. 

Now I was playing around with openupgrade and I managed to upgrade to odoo11, but I had to uninstall account_analytic_analysis before (as well as all other non-odoo-standard modules). 

Is there any (easy) way to upgrade odoo without loosing my contract data? From what I understand the oca contract module has the same table structure, so upgrading without loosing my data should be possible somehow, I guess...

Thank you :-)

**Comment by pedrobaeza** [comment]
You don't need to uninstall it. Just put contract module in v9 migration step and there are the migration scripts there for adapting data from one module to the other.

**Comment by peter2018abc** [comment]
thank you for your input.
Can you point me to a how-to? I am looking through https://doc.therp.nl/openupgrade/ but I am not sure where to look. I've been using the automated migration script before. I guess I'll have to do a manual migration now....?

Thank you.

**Comment by pedrobaeza** [comment]
Use the manual procedure from the guide having the contract addon available when migrating to v9.

**Comment by peter2018abc** [comment]
Thank you. I simply added the contract module to the odoo-9 addon folders of openupgrade and restarted the automated migration script. Worked perfectly!
