### ISSUE TITLE
[11.0] contract: Button "Create invoices" throws error

### ISSUE THREAD

**Issue by aitorbouzas** [OCA/contract#269]
When in debug mode, the button "Create invoices" appears and you can call through it the `recurring_create_invoice` method. The problem is this method gets the optional parameter `limit`. This `limit` gets the context values when calling it through the button so it throws an error here:
https://github.com/OCA/contract/blob/d31ee5757cdae5020b689fb778141e1f99810dba/contract/models/account_analytic_account.py#L291

**Comment by pedrobaeza** [comment]
It's a keyword argument, so optional, and this is why it is checked first if it contains any value. I don't see here any error.

**Comment by aitorbouzas** [comment]
The thing is it contains values when launching it from the UI because it gets the `context` values. When making the comparison it throws an error because you are comparing a number (`len(invoices)`) with a dict (`limit` containing `context` values) At least that's what's happening in my system, let me check runbot.

**Comment by aitorbouzas** [comment]
@pedrobaeza reproduced on runbot. We need a parser method for the UI button.

**Comment by pedrobaeza** [comment]
Or just explicitly pass a False limit in the method called by the button.

**Comment by aitorbouzas** [comment]
I'll PR.
