### ISSUE TITLE
agreement_sale error creating sale order

### ISSUE THREAD

**Issue by karlggest** [OCA/contract#271]
Hi!
I'm testing odoo v11.0 and agreements module. I try install sales, agreements and agreements sale from this repository and I get the following error:

> Error:
> Odoo Server Error
> 
> Traceback (most recent call last):
>   File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
>     return super(JsonRequest, self)._handle_exception(exception)
>   File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
>     raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
>   File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
>     raise value
>   File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
>     result = self._call_function(**self.params)
>   File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
>     return checked_call(self.db, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
>     return f(dbname, *args, **kwargs)
>   File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
>     result = self.endpoint(*a, **kw)
>   File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
>     return self.method(*args, **kw)
>   File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
>     response = f(*args, **kw)
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 935, in call_button
>     action = self._call_kw(model, method, args, {})
>   File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 923, in _call_kw
>     return call_kw(request.env[model], method, args, kwargs)
>   File "/opt/odoo/odoo11/odoo/api.py", line 689, in call_kw
>     return call_kw_multi(method, model, args, kwargs)
>   File "/opt/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
>     result = method(recs, *args, **kwargs)
>   File "/opt/odoo/odoo11/addons/sale/models/sale.py", line 537, in action_confirm
>     self._action_confirm()
>   File "/opt/odoo/odoo11-custom-addons/agreement_sale/models/sale_order.py", line 32, in _action_confirm
>     self.env['agreement.line'].create({
>   File "/opt/odoo/odoo11/odoo/api.py", line 760, in __getitem__
>     return self.registry[model_name]._browse((), self)
>   File "/opt/odoo/odoo11/odoo/modules/registry.py", line 181, in __getitem__
>     return self.models[model_name]
> KeyError: 'agreement.line'

What I need to make this module works?

Thanks for your help

EDIT: seems my agreement modules stills was which i've download form odoo.com/apps. Ty

**Comment by max3903** [comment]
@karlggest Can you try upgrading the `agreement` module before installing `agreement_sale`?
