### ISSUE TITLE
[10.0.4.2.0] Error after update: failed to generate requrring invoices

### ISSUE THREAD

**Issue by victorkob** [OCA/contract#272]
Hi,
I've updated module from git and now have an error with requrring invoice generating both automatic and manual:
> relation "account_analytic_invoice_line_account_analytic_tag_rel" not exist

Log:

> INFO test3 odoo.sql_db: bad query:  SELECT   account_analytic_invoice_line_account_analytic_tag_rel.account_analytic_invoice_line_id, account_analytic_invoice_line_account_analytic_tag_rel.account_analytic_tag_id FROM account_analytic_invoice_line_account_analytic_tag_rel, "account_analytic_tag"
>                    WHERE 1=1 AND account_analytic_invoice_line_account_analytic_tag_rel.account_analytic_invoice_line_id IN (4) AND account_analytic_invoice_line_account_analytic_tag_rel.account_analytic_tag_id = account_analytic_tag.id
>                     ORDER BY "account_analytic_tag"."id"    OFFSET 0

> 2019-02-03 20:47:56,602 7488 ERROR test3 odoo.http: Exception during JSON request handling.
> Traceback (most recent call last):
> File "/opt/odoo10/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
> File "/opt/odoo10/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
> File "/opt/odoo10/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
> File "/opt/odoo10/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
> File "/opt/odoo10/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
> File "/opt/odoo10/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
> File "/opt/odoo10/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
> File "/opt/odoo10/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
> File "/opt/odoo10/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
> File "/opt/odoo10/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
> File "/opt/odoo10/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
> File "/opt/addons/10/contract/models/account_analytic_account.py", line 290, in recurring_create_invoice
    invoices |= contract.with_context(ctx)._create_invoice()
> File "/opt/addons/10/contract/models/account_analytic_account.py", line 257, in _create_invoice
    invoice_line_vals = self._prepare_invoice_line(line, invoice.id)
> File "/opt/addons/10/contract/models/account_analytic_account.py", line 192, in _prepare_invoice_line
    invoice_line.analytic_tag_ids |= line.analytic_tag_ids
> File "/opt/odoo10/odoo/fields.py", line 915, in __get__
    self.determine_value(record)
> File "/opt/odoo10/odoo/fields.py", line 1017, in determine_value
    record._prefetch_field(self)
> File "/opt/odoo10/odoo/models.py", line 3078, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
> File "/opt/odoo10/odoo/models.py", line 3018, in read
    self._read_from_database(stored, inherited)
> File "/opt/odoo10/odoo/models.py", line 3172, in _read_from_database
    field.read(fetched)
> File "/opt/odoo10/odoo/fields.py", line 2400, in read
    records._cr.execute(query, where_params)
> File "/opt/odoo10/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
> File "/opt/odoo10/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
> ProgrammingError: ОШИБКА:  отношение "account_analytic_invoice_line_account_analytic_tag_rel" не существует
> LINE 1: ...unt_analytic_tag_rel.account_analytic_tag_id FROM account_an...
                
What can I do?

Thanks

**Comment by pedrobaeza** [comment]
Have you updated the module clicking on the "Upgrade" button or using -u contract on the command line?

**Comment by victorkob** [comment]
I'm sorry, this is my childish mistake. Checked in debug mode: Apps > Updates, I haven't update module in all databases.

Thanks
