### ISSUE TITLE
Validate invoice permissions

### ISSUE THREAD

**Issue by ghost** [OCA/contract#274]
Hi, we have succesfully installed the module and created some contracts. Cron is working ok and creating the invoices, but the problem is that only the admin can "validate" them.

Financial user have max permissions on Accounting module. Could someone help?. Thanks.

**Comment by pedrobaeza** [comment]
This is because you have a mix of companies in your data (journals, accounts or so on). Try in a single company environment or fix that mix.

**Comment by ghost** [comment]
Does this means that the contracts module does not work on multicompany?.

The error received in spanish is "No se ha podido completar la operación por restricciones de seguridad. Contacte con su administrador del sistema. (Tipo de documento: Analytic Line, Operación: write)"

**Comment by pedrobaeza** [comment]
Yes, it works, but you have to adjust properly the values. The specific error you are mentioning now is about analytic lines, and in this case it can happen in a single-company environment also if you haven't properly adjust the permissions on the user that is creating the invoice (it has to be invoicing manager).

**Comment by ghost** [comment]
Thanks for your response but it seems is not that permission. User is invoicing manager and I have also gave her several checks permissions related to analytic accounting but doesn't work.

I attach specific permissions to try to clarify the issue.

![captura](https://user-images.githubusercontent.com/34126403/52408443-32304100-2ad3-11e9-8f62-959f90fed8d2.JPG)

**Comment by pedrobaeza** [comment]
Check which record rules are applying to that model. Any way, this is not related to the module itself.
