### ISSUE TITLE
[11.0] contract: Project manager unable to create a project

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [OCA/contract#278]
A user with only project manager (and employee) permission group established is not able to create a project.
```
Sorry, you are not allowed to access this document. Only users with the following access level are currently allowed to do that:
- Accounting & Finance/Billing Manager
- Technical Settings/Show Full Accounting Features
- Accounting & Finance/Billing
- Inventory/User
- Sales/User: Own Documents Only
- Inventory/Manager
- Sales/User: Own Documents Only
- Purchases/User
- Purchases/Manager
- Purchases/Manager
- Sales/User: Own Documents Only

(Document model: account.journal) 

```

Update (04/05/2020):

 * When installing addon contract and trying to create a new project with a Project Manager user:

![image](https://user-images.githubusercontent.com/23120306/80956437-88d51980-8e01-11ea-9670-932d7097b97b.png)

Kind regards,
Luis

**Comment by pedrobaeza** [comment]
Is this still happening? Which module?

**Comment by ljsalvatierra-binovo** [comment]
I'll try to reproduce it today and give you the results.

**Comment by pedrobaeza** [comment]
Well, I mean the module in this repository that causes your problem.

**Comment by ljsalvatierra-binovo** [comment]
Yes, sorry, the module is contract. And yes, I've been able to reproduce it again with the last commit of OCB and contract repos.

![image](https://user-images.githubusercontent.com/23120306/80956365-604d1f80-8e01-11ea-8542-6a4a6a9a4dca.png)

**Comment by pedrobaeza** [comment]
OK, then it should remain opened. I have tagged and adapt title a bit.

**Comment by ljsalvatierra-binovo** [comment]
Perfect, thank you :)
