### ISSUE TITLE
Portal module for v11

### ISSUE THREAD

**Issue by Boca13** [OCA/contract#285]
Hello,

I was wondering if there is a module for v11 similar to website_portal_contract, available for v10. I'm seeking to show customers contract information.

https://apps.odoo.com/apps/modules/10.0/website_portal_contract/

I haven't seen anything or any initiative to port it.

Thank you.

**Comment by pedrobaeza** [comment]
No, there isn't any for now. You can contribute developing it or fund someone for doing it.
