### ISSUE TITLE
[10.0][BUG] agreement_account duplicate agreement

### ISSUE THREAD

**Issue by ygol** [OCA/contract#289]
when trying to duplicate (menu action / duplicate) an agreement. There is an error message:

> Odoo Warning - Validation Error
> The operation cannot be completed, probably due to the following:
> - deletion: you may be trying to delete a record while other records still reference it
> - creation/update: a mandatory field is not correctly set
> 
> [object with reference: code - code]

**Comment by pedrobaeza** [comment]
Is this still happening?

**Comment by ygol** [comment]
On the runbot V10.0 it doesn't work so **it is still hapening.**

On the runbot V12.0 it works so not happening anymore.

**Comment by pedrobaeza** [comment]
Then let's close it as fixed in later versions. If someone wants to fix it for this old version, he/she can propose a PR.
