### ISSUE TITLE
[IMP][10.0] different address for invoce and delivery

### ISSUE THREAD

**Issue by mamojdick** [OCA/contract#302]
Hi,
i tried this [IMP] in  contract/models/account_analytic_account.py , what do you think about?

![immagine](https://user-images.githubusercontent.com/48570656/55265119-24976c00-5277-11e9-8b4c-d439a6f3f0cd.png)

        shipping_id = (
            self.partner_id.address_get(['delivery'])['delivery'] or
            self.partner_id.address_get(['invoice'])['invoice']
        )
        invoice = self.env['account.invoice'].new({
            'reference': self.code,
            'type': 'out_invoice',
            'partner_id': self.partner_id.address_get(
                ['invoice'])['invoice'],
            'partner_shipping_id': shipping_id,

**Comment by pedrobaeza** [comment]
The onchange performed for partner_id in the invoice should be enough for getting the delivery address. Why do you need this?

**Comment by mamojdick** [comment]
When the invoice is generated by recurrence, the delivery address is blank. The onchange is activated manually. I need to validate the invoice by one click with all addresses populated. 
I think that's it or isn't it?

**Comment by pedrobaeza** [comment]
Closing as no PR has been done and it's an old version.
