### ISSUE TITLE
[IMP][12.0] agreement_legal: include o2m field in dynamic fields

### ISSUE THREAD

**Issue by ygol** [OCA/contract#311]
How would we allow a user to add a o2m fields (and chose subsequent fields.) in a dynamic entry?
for example:
the user would like to add in a section; a table with all records from the o2m lines_ids and list the some fields from this related table: product_id, qty, uom.

TIA

**Comment by max3903** [comment]
This start to look like a report designer or studio.

Quick answer is to enter Jinja2 or QWeb code directly in the dynamic entry and make sure it is interpreted when printing.

**Comment by ygol** [comment]
> 
> 
> This start to look like a report designer or studio.
> 
> Quick answer is to enter Jinja2 or QWeb code directly in the dynamic entry and make sure it is interpreted when printing.

so we need a way to escape the jinja2/QWeb code in the dynamic entry. Right? How would I get it interpreted?

**Comment by max3903** [comment]
@ygol The user would need to enter something like (QWeb example):

```
<table>
    <th>
        <td>Product</td>
        <td>Description</td>
        <td>Quantity</td>
    </th>
    <tr t-foreach="agreement_id.line_ids" t-as="l">
        <td>l.product_id</td>
        <td>l.name</td>
        <td>l.quantity</td>
    </tr>
</table>
```

**Comment by ygol** [comment]
> @ygol The user would need to enter something like (QWeb example):
> 
> ```
> <table>
>     <th>
>         <td>Product</td>
>         <td>Description</td>
>         <td>Quantity</td>
>     </th>
>     <tr t-foreach="agreement_id.line_ids" t-as="l">
>         <td>l.product_id</td>
>         <td>l.name</td>
>         <td>l.quantity</td>
>     </tr>
> </table>
> ```

yes I get this part but how do I escape it in the html field to get it interpreted by the render function?

**Comment by ygol** [comment]
> 
> 
> > @ygol The user would need to enter something like (QWeb example):
> > ```
> > <table>
> >     <th>
> >         <td>Product</td>
> >         <td>Description</td>
> >         <td>Quantity</td>
> >     </th>
> >     <tr t-foreach="agreement_id.line_ids" t-as="l">
> >         <td>l.product_id</td>
> >         <td>l.name</td>
> >         <td>l.quantity</td>
> >     </tr>
> > </table>
> > ```
> 
> yes I get this part but how do I escape it in the html field to get it interpreted by the render function?

@max3903 can you help?

**Comment by max3903** [comment]
@ygol 

Same as the other fields: you compute the dynamic field from the user entry:
https://github.com/OCA/contract/blob/12.0/agreement_legal/models/agreement_appendix.py#L22
https://github.com/OCA/contract/blob/12.0/agreement_legal/models/agreement_appendix.py#L90

and include it in the view:
https://github.com/OCA/contract/blob/12.0/agreement_legal/report/agreement.xml#L65

**Comment by ygol** [comment]
@max3903 I am almost there. Here's the syntax that works when added to the html field to insert a table referencing a o2m:

```
<table class="table table-bordered">
    <tbody>
        <tr>
            <th>title 1</th>
            <th>title 2</th>
        </tr>
        <tr>
            <td><% for l in object.agreement_id.line_ids %> </td>
        </tr>
        <tr>
            <td>
                <% print l.name %>
                <% print l.product_id.name %>
            </td>
            <td><% print l.quantity %> /MWh cumac ou
            </td>
        </tr>
        <tr>
            <td>
                <% endfor %>
            </td>
            <td>
            </td>
        </tr>
    </tbody>
</table>
```
I still need to figure:
1. how to use/include a control structure:
```
% if x==5:
    this is some output
% endif
```
2. how to use a 2nd loop inside the first one to be able to add the values of a O2M inside the first O2M.

**Comment by max3903** [comment]
```
{% if 'priority' in data %}
    <p>Priority: {{ data['priority'] }}</p>
{% endif %}
```

https://stackoverflow.com/questions/40620823/if-statement-in-jinja2-template/40620902
