### ISSUE TITLE
How to define a prefix to the section's numbering

### ISSUE THREAD

**Issue by ygol** [OCA/contract#325]
It will be useful to be able to replace the simple numbering for the sections with a provided prefix in the type of:
"Section 1", "Section 2", ...
or
"Article 1", Article 2: ...

**Comment by max3903** [comment]
Why not use the title?

**Comment by ygol** [comment]
because then you would have to modify all the titles when you remove a section.

**Comment by max3903** [comment]
You can do it with CSS:
https://stackoverflow.com/questions/5568229/how-can-i-prefix-ordered-list-item-numbers-with-a-static-string-using-css

**Comment by ygol** [comment]
thanks @max3903 
It works nicely by adding:
 

>                                                        <style>
>                                                             ol {
>                                                             counter-reset: item;
>                                                             list-style-type: none;
>                                                             }
>                                                             ol li:before {
>                                                             content: 'Clause ' counter(item, decimal) '. ';
>                                                             counter-increment: item;
>                                                             }
>                                                         </style>
