### ISSUE TITLE
[12.0] agreement_legal: how to reference a certain specific section?

### ISSUE THREAD

**Issue by ygol** [OCA/contract#326]
Let say I have 5 sections. When the report is generated the templating will number them 1 to 5.
**Is there a way to reference the 3rd section?**

for example:

I would like to have a text in the 4th section that goes: 

> "as stated in article %3%, blablabla "

now in the case I delete the 2nd section the text would automatically read:

> "as stated in article %2%, blablabla "

TIA

**Comment by max3903** [comment]
I believe you can achieve this with anchor and a meaningful name for the id.

something like
```
<a id="confidential_information"/>
[...]
<a href="#confidential_information">Confidential Information section</a>
```

**Comment by ygol** [comment]
thank you @max3903 but I need it in a pdf. It is the number I would like to target/use

**Comment by max3903** [comment]
Webkit is converting from html + css to pdf...
