### ISSUE TITLE
[12.0][BUG] Agreement is showing the wrong view

### ISSUE THREAD

**Issue by kittiu** [OCA/contract#327]
I installed both agreement and agreement_legal modules. I saw in code that agreement_legal has much bigger view than the view from agreement module.
But when I play with it, Agreement still show the view from agreement module, which has only few field.
![image](https://user-images.githubusercontent.com/1973598/57581775-8be74380-74e6-11e9-97af-4fd8c4cd1abf.png)

Only when I go to view menu and delete all the views from module agreement, that I got the more informative view.
![image](https://user-images.githubusercontent.com/1973598/57581801-e4b6dc00-74e6-11e9-921d-745e6dec0893.png)

May be there is no priority in the view? And somehow the base module still takes priority.

**Comment by bealdav** [comment]
Have you tested agreement_sale ?

**Comment by kittiu** [comment]
Yes, and the result of the agreement form view is the same (show only 6 fields)

![image](https://user-images.githubusercontent.com/1973598/57590422-d227bb80-7555-11e9-9779-8b8ad34a54db.png)

And when I click to install agreement_sale, the Agreement menu moved to Sales/Config
But when I upgrade the "agreement" again, the menu Agreement move back to its own parent menu too.

May be because the sorting of view somehow that happen only on my machine database locale, etc.... ?

**Comment by bealdav** [comment]
cc @max3903

**Comment by max3903** [comment]
Hello @kittiu,

I installed agreement_legal and when I create an agreement in Agreement, I get what you called the bigger view.

What are the steps you used to see the view from the agreement module?

**Comment by kittiu** [comment]
@max3903 I do the exact following step
1. Create new database = odoo12_contract (country = Thailand)
2. Install module "agreement_legal"

Open an Agreement and I get the small view. So my guess that your instance do not have problem is because of locale when you installed postgres. I experienced the sorting of database record can be different for different installation.

In that case, we can fix by  add priority to the view, and now it works.

+        <field name="priority" eval="1"/>
         <field name="arch" type="xml">
             <form string="Agreements Form">
                 <header>

**Comment by max3903** [comment]
@kittiu Like this https://github.com/OCA/contract/pull/330/files?

**Comment by kittiu** [comment]
Yes!
