### ISSUE TITLE
[12.0] Question on Agreement vs Contract.

### ISSUE THREAD

**Issue by kittiu** [OCA/contract#328]
Hi, I am playing around with the agreement and contract module. On v11, I saw some attempt to link analytic (the contract) with agreement. There was even "agreement_id" in account.analytic.line which seem to get the financial performance of the agreement (in Agreement's Performance tab). However, from the source code that I dig, I can't find anywhere that assign agreement_id to analytic line.

So, I move to look into v12. Now, in v12, I saw the linkage between them is being removed, which does seem to me, the 2 module (agreement and contract) are now intended to be separated. Tab Financial was also removed in v12. However, the tab Performance still exits with following statement,
![image](https://user-images.githubusercontent.com/1973598/57581845-ab32a080-74e7-11e9-888e-2fa9ce3accd9.png)

Question is:
- By design, is it intended to make agreement and contract totally separated?
- What is the meaning of Performance tab? or what is the intention?

Thank you so much!

**Comment by sbidoul** [comment]
In my understanding, the `contract` module is specifically for managing recurring invoicing.

In the future, contracts will be decoupled from analytic accounts. Preliminary work for this is split has been done in https://github.com/OCA/contract/pull/207.

It makes sense to provide links between contract and agreement as a glue module.

**Comment by kittiu** [comment]
@sbidoul thank you for the answer. May I summarize my understanding, please correct if I am wrong.

- **Contracts will be decoupled from analytic accounts** --> contracts will not inherit account.analytic.account like project anymore. It will of of its own object.
- **It makes sense to provide links between contract and agreement as a glue module** --> It should have linkage in the future, but it is not there yet, and now it is still no link.

By the way, from the previous question about Performance tab, I see there is only static view. So it is now the placeholder of unfinished work, right?

**Note:** I am interested in this module as we may have work around it. Wanted to know the current status.

**Comment by sbidoul** [comment]
> Contracts will be decoupled from analytic accounts --> contracts will not inherit account.analytic.account like project anymore. It will of of its own object.

Correct, that is the plan. When it will happen is not clear, as I would prefer to merge #207 first, and then work further on the split, with a proper migration.

> It makes sense to provide links between contract and agreement as a glue module --> It should have linkage in the future, but it is not there yet, and now it is still no link.

That is my understanding yes. Disclaimer: I'm not familiar with the agreement module.

If you are interested in recurring invoicing, #207 is the best place to start.

**Comment by kittiu** [comment]
@sbidoul thank you very much for clarification :) Make more sense to me now.

**Comment by max3903** [comment]
@kittiu 

`agreement_legal` module aims to support the activities of a legal team in a company and allow them to manage the content of legal documents like agreements, contracts, letter of intention.

In `agreement_legal_sale`, we have the relationship between agreement and analytic account to track the financial performance of the agreement. The performance tab should be removed and a smart button to analytic lines should be added.
