### ISSUE TITLE
product contract migration to V12 and adapt to point of sale

### ISSUE THREAD

**Issue by celm1990** [OCA/contract#334]
Hi comunity, 

I was  intereste for migrate module product_contract to Version 12, but I need product_contract for point of sale, current module worked with sales order.
Think is need moved [this fields](https://github.com/OCA/contract/blob/10.0/product_contract/models/product_template.py#L11-L15) to common module([module contract](https://github.com/OCA/contract/tree/12.0/contract) if I can do changes on stable version or OCA has same policy as Odoo??)

Create two modules:

1. `product_contract_sale`(rename current module product_contract, inherit of modules: sale and contract)
2. `product_contract_pos`(new module than inherits modules: point_of_sale and contract

What do you think?

**Comment by sbidoul** [comment]
@sbejaoui can you provide pointers to the current PRs here?

**Comment by pedrobaeza** [comment]
For me, you should keep `product_contract` as is and then put on top of it the new module `product_contract_pos`.

**Comment by celm1990** [comment]
> For me, you should keep `product_contract` as is and then put on top of it the new module `product_contract_pos`.

but if only you need `point of sale`(not need `sale `module)?, at inherit of `product contract `add dependency of `sale `module, is unnecessary to me.

**Comment by pedrobaeza** [comment]
Yeah, but it's not the normal flow, and changing current base only for that abnormal flow will cause a lot of migration problems.

**Comment by pedrobaeza** [comment]
(sorry, closed by accident)

**Comment by celm1990** [comment]
> Yeah, but it's not the normal flow, and changing current base only for that abnormal flow will cause a lot of migration problems.

Ok, but if not add dependencies to `product_contract`, and add [this fields ](https://github.com/OCA/contract/blob/10.0/product_contract/models/product_template.py#L11-L15) on product, can repeat fields definition, but not add dependency is other option.

module `product_contract`:

- Add fields on product template
- add logic for create contract from sales order lines with products with contract template configured
- dependency only to module contract

Module `product_contract_pos`
- Add fields on product template
- add logic for create contract from pos orders lines with products with contract template configured
- dependency only to module `contract`(not dependency to `product_contract `and `sale`(indirectly))

**Comment by pedrobaeza** [comment]
As said, I prefer that `product_contract_pos` depends on current `product_contract`.

**Comment by sbejaoui** [comment]
The migration for product_contract to v12 is in PR #208 with many improvement and new features.

**Comment by pedrobaeza** [comment]
Closing this for now.
