### ISSUE TITLE
[IMP] agreement: Add products on PDF, email to customer and access on the portal

### ISSUE THREAD

**Issue by amnyqb** [OCA/contract#341]
- [ ] Showing ordered products in the PDF
Under the agreement tabs, there is a tab for products, filling the products doesn't show when printing the agreement document. Filling the products tabs should make it easy to instantiate the order and invoice.

- [ ] Add a button to send the contract PDF to the customer and keep email discussion in the chatter
It would be better to allow sending the agreement to the client and get the client feedback, and include the feedback under the document revision history. 

- [ ] Integration with the website
Add the contracts on the portal. 
Client should interact with the company via the website similar to invoices and orders.

**Comment by pedrobaeza** [comment]
These are no bugs, but improvements, isn't it?

**Comment by amnyqb** [comment]
point no.1 seems like a problem. 

for 2 and 3, yes, you can consider them as improvements.

**Comment by max3903** [comment]
@amnyqb This is the current state of the module and the expected features set. I understand it doesn't meet your requirements. If you want to work on this together, please contact us by email at contact@opensourceintegrators.com.

CC: @gmader, @richosi

**Comment by pedrobaeza** [comment]
No more answers, so closing.
