### ISSUE TITLE
Add Pro-forma option

### ISSUE THREAD

**Issue by bylli79** [OCA/contract#347]
Is it possible to insert pro-forma creation as an option?
Thank you

**Comment by pedrobaeza** [comment]
Which version?

**Comment by bylli79** [comment]
The version is this: 12.0.1.0.0

**Comment by pedrobaeza** [comment]
There is no pro-forma invoice, but sales order. Use `contract_sale_generation`, which is in pull requests right now.

**Comment by bylli79** [comment]
Thanks for your help
