### ISSUE TITLE
[IMP] agreement_serviceprofile: Add a state field

### ISSUE THREAD

**Issue by max3903** [OCA/contract#349]
# agreement.serviceprofile

- [x] Add a selection field State (state) with Draft, In Progress, Suspended, To Renew, Terminated, Cancelled
- [x] Add a many2one field "Service" (product_id) to product.template. The list of products is filtered with a domain: type = service.
- [x] Add the clickable workflow on the form view to move from one state to another
- [x] Add a Kanban view in the Dashboard menu

**Comment by max3903** [comment]
FYI @patrickrwilson @ygol

**Comment by brian10048** [comment]
@max3903 should the state be configurable and create a new object for it with the states you mentioned as data?

**Comment by max3903** [comment]
@brian10048 I guess you are asking because you have a different workflow... so yes!
