### ISSUE TITLE
Why analytic account?

### ISSUE THREAD

**Issue by jguenat** [OCA/contract#352]
Hello,

First thanks for this module, it's very useful :)

I have a question regarding the base business logic design of this contract module. 
Why is each contract an analytical account? Could it work without inheriting account.analytic.account model?
Because if I want to use odoo analytic accounts to do other things, the contracts generates a lot of "polluting" analytic accounts.
I'm new to business logics so if someone can enlighten me about this it would be great 

Thanks a lot!

**Comment by sbidoul** [comment]
This is for historical reasons (inherited from Odoo 8 and before).

#207 splits contracts from analytic accounts, among other changes.
