### ISSUE TITLE
agreement_legal_sale: README mentions BOM

### ISSUE THREAD

**Issue by gurneyalex** [OCA/contract#371]
The README says 

```
the products on the SO with BOM are added as service profile on the agreement
```

I see nothing such in the source code. What I see is that lines with a product which is_serviceprofile = True trigger the creation of  as serviceprofile (which fails, see #370)

**Comment by max3903** [comment]
@gurneyalex Documentation has been updated. There is no dependency on MRP yet. That may come later in an additional module.
