### ISSUE TITLE
"Does not create the Delivery Order nor the Manufacturing Order

### ISSUE THREAD

**Issue by fdesrosiers3** [OCA/contract#377]
module: contract
version: 12.0

**Steps to reproduce**
- ...Create Contract, Create Invoice.  

**Current behavior**
   There is
      - no way to calculate the delivery price.
      -  for products that are to be manufactured, no work order is created.
      -  no delivery document created. So, I do not know the scheduled delivery
 
**Expected behavior**
         - delivery method button
          - work orders for products that are to be manufactured
           - delivery document created.

**Comment by pedrobaeza** [comment]
`contract` are not for all that operations. You can try `contract_sale_generation` (at the moment, on v10, but with PR to 11.0) for generating sales orders, that triggers all you mention on confirmation.

**Comment by fdesrosiers3** [comment]
Hello Pedro, I am on V12, so the contract_sale_generation may not work.
Any chance of getting this on v12

**Comment by pedrobaeza** [comment]
No if nobody works on it.

**Comment by fdesrosiers3** [comment]
There is a very complicated work around.
Which is install contract_sale_invoicing.
for each period of the recurring invoice, each time create a sales order with the same analytic account as the customer contract.  But that is way too hard for end users
