### ISSUE TITLE
Create invoices ahead of time for cashflow forecast

### ISSUE THREAD

**Issue by utillity** [OCA/contract#380]
Hi,

first of all thanks for this great module! I would like to be able to set the amount of days the invoice should be created ahead of the next billing period, so that it can be reflected in the cashflow forecast.

regards, Tilli

**Comment by pedrobaeza** [comment]
Which "cashflow forecast" are you talking about?

**Comment by utillity** [comment]
the open invoices amount to be paid

**Comment by pedrobaeza** [comment]
Yeah, but how do you check that? Only seeing invoices?

**Comment by pedrobaeza** [comment]
@sbidoul did you finally do something about this?

**Comment by sbidoul** [comment]
We made https://github.com/OCA/contract/pull/283 for this purpose.

**Comment by utillity** [comment]
I use the report in conjuntion with the analytics accounts which will also show invoices not yet paid.

**Comment by utillity** [comment]
feel free to close this issue, then

**Comment by pedrobaeza** [comment]
Closing as stated.
