### ISSUE TITLE
Delete and recreate invoice

### ISSUE THREAD

**Issue by utillity** [OCA/contract#381]
Hi,

if a auto-generated invoice has been deleted by accident, is there a way to regenerate the last invoice date by checking the actual invoices? Currently, the field "Last Date Invoiced" is not editable and will cause incorrect #START# replacement on generating the replacement invoice.

regards, Tilli

**Comment by sbejaoui** [comment]
Hi, 
For now, you have to duplicate an existing invoice generated by the contract and change the dates.

When we added this field, we mainly focused on data integrity, so we set it to readonly.
In the real world, the wrong manipulations happen, so we have to find a way to solve this kind of scenario.

I had thought of a security group that allows some users to change this field and take data integrity data under their responsibility.

Regards,

**Comment by utillity** [comment]
ok, thanks. either that or a button "recalculate last date invoiced"

**Comment by sbejaoui** [comment]
you mean odoo should look for the last invoice linked to the contract line and define the last date invoiced accordingly?

**Comment by utillity** [comment]
> 
> 
> you mean odoo should look for the last invoice linked to the contract line and define the last date invoiced accordingly?

yes, only on request (if a corresponding button is pressed)

**Comment by flachica** [comment]
I make a wizard to update this field. But this is total insecure. Save the start and end dates in invoices can be help us, but is not simple
