### ISSUE TITLE
move some concepts out of agreement_legal

### ISSUE THREAD

**Issue by gurneyalex** [OCA/contract#382]
For a development I'm working on, I need some concepts on agreements that are introduced by agreement_legal, but without all the bells and whistles that are provided by that module. 

mainly:

* the agreement.type model (without necessary the subtypes)
* the is_template field on agreement

I propose making a PR which would move these definitions in the base agreement module on which agreement_legal depends. Alternatively, I could create a new module, but it seems a pity to tackle adding a dependency in agreement_legal.

**Comment by pedrobaeza** [comment]
For me seems reasonable

@max3903 ?

**Comment by gurneyalex** [comment]
@max3903 @bealdav is this ok with you?

**Comment by bealdav** [comment]
@gurneyalex It sounds possible for me to be compatible with our use cases if these fields are not required.
Just a question. What is the impact (behavior) in other models like sales ?

**Comment by gurneyalex** [comment]
@bealdav I would like to keep the agreement module as neutral as possible. Currently there is no real business logic in there. AFAIU, you are using this module to trigger onchange methods on the SO (and possibly in other places), which is fine, but I could find a way to cover my customer's needs with just this: they call for a kind a dynamic agreement on the SO which is a combination of things which come from some customer preferences and other things which come from an agreement type, and then can be further customized on a case by case basis.

The fields which are introduced in agreement_legal provide a typology I can use to move in that direction, but agreement_legal also pulls a huge load of stuff I don't need. 

I'll make a PR to move the fields in a clean way, and another explaining how I plan to use this in our business case.
