### ISSUE TITLE
Payment Terms and Comment area missing

### ISSUE THREAD

**Issue by kitatek** [OCA/contract#384]
Hello,

When invoices are created two fields are populated in an inconvenient manner:

1. the payment term is blank
2. the long description text area below the invoice is filled with the company default terms 

The proper implementation would rather be:

1. the payment term is pulled from the contract payment term field (hence to be added in contract model and form)
2. the long description should be taken from the contract comment field (to be added too)

This reproduces better the real business situation of recurring contracts.

Thanks.

**Comment by pedrobaeza** [comment]
Odoo version? Steps to reproduce the problem?

**Comment by kitatek** [comment]
Odoo 10 community

Steps:

1. In menu Sales - Configurations - Settings - Quotations & Sales - Default Terms and Conditions *  : add some default sales terms.
2. Create a contract
3. Generate an invoice
4. The invoice has a blank Payment Term, and the Comment area in the printed invoice includes the  Default Term and Conditions

**Comment by pedrobaeza** [comment]
But has the partner a payment term set?

About the default term and conditions, what do you expect to appear there?

**Comment by kitatek** [comment]
Invoice generation from a contract should have consistent behavior with invoice generated from a sales order : 
payment term taken from the contract
comment area taken from the contract

I did not check the partner payment term, as actually I usually set it on the Sales Order. Will test and let you know.

**Comment by kitatek** [comment]
OK, it works when setting a partner Payment Term, that is not perfect but a fair workaround.
Thank you Pedro for the hint ! 

For the invoice comment area, any thoughts ?

**Comment by pedrobaeza** [comment]
Contract comments are internal comments that are not supposed to be passed to the invoice comment area. The field was not intended for that.

**Comment by kitatek** [comment]
Actually I did not see any contract comment field in the form, I am referring to the Invoice comment field, that is in the form and printed in the PDF report for the customer.

Actually, to further think about it, even the default behavior from Sales order to Invoice is not perfect: T&C in the order do not conveniently pas as-is to the Invoice.
Ideally, there would be several fields:

1. T&C portion passable from order to invoice (e.g. note to refer to the terms in the Order)
2. T&C portion not passable from Order to invoice (e.g. Order T&C plus sign-off area)
3. Both should be set in the Order form


Same for the contract as for the Order:

1. One area printed with the contract only (e.g. Contract T&C plus sign-off area)
2. T&C portion passable from contract to invoice (e.g. note to refer to the terms in the contract)
3. Both should be set in the contract form

**Comment by pedrobaeza** [comment]
As said, that are missing features and nobody has needed for now, so that's why it's not implemented. You can develop that feature or fund someone to do it.

**Comment by kitatek** [comment]
We have never developed on Odoo but that seems tempting.
I would see those things to add:

1. one text area for contract T&C and sign-off
2. printing of this text in the PDF report
3. one text area to be passed to Invoices
4. passing this text to the invoice when creating it

Does this really require development or can be done by configuration only (like changing the PDF report XML file, and adding the required fields in model, forms/views, and actions, all from the GUI in developer mode) ?

Thanks for any guidance how to accomplish this.

**Comment by pedrobaeza** [comment]
It requires development, so yo need developer skills for that I'm afraid. Any way, you should go IMO to 12.0 first for taking advantage of lots of improvements in Odoo itself and in this module in particular
