### ISSUE TITLE
Request improvement in Contracts: Show contracts in Portal

### ISSUE THREAD

**Issue by rafaelbn** [OCA/contract#385]
Hi,

I would be very nice that Customer can see their contracts in the Odoo Portal like quotations, sale orders, invoices and so on...

Now in v12 we don't need website :smile: In the past we had:

- https://github.com/OCA/contract/issues/45
- https://github.com/OCA/contract/tree/10.0/website_portal_contract

Something similar as we did with Business Requirements in https://github.com/OCA/business-requirement/blob/12.0/business_requirement/views/br_portal_templates.xml

Thanks
Regards

cc @tecnativa

**Comment by pedrobaeza** [comment]
I wrote that as a track for OCA Days code sprint: https://docs.google.com/document/d/10e0nZKsSK2Fm-_Me-g3yoyVEVpKQK9uUqCmRZ8LIvjw/edit#heading=h.b0u15ky7wz0g

**Comment by pedrobaeza** [comment]
Already done.
