### ISSUE TITLE
Template fallback

### ISSUE THREAD

**Issue by Evenecer** [OCA/contract#389]
Hello

when I create a contract and I want to print it I get an error

500: Internal Server Error
Template fallback
An error occured while rendering the template 1944.

If this error is caused by a change of yours in the templates, you have the possibility to reset one or more templates to their factory settings.

 report_contract_document

I give the reset and the error is not fixed

rastreando un poco mas
Error message:

'contract.contract' object has no attribute 'recurring_invoice_line_ids'
????????

**Comment by pedrobaeza** [comment]
You are not indicating the version, but it seems you haven't updated the module in the DB.

**Comment by pedrobaeza** [comment]
Closing as no answer
