### ISSUE TITLE
[12.0] - product_contract module dependency to sale_start_end_dates

### ISSUE THREAD

**Issue by sbejaoui** [OCA/contract#395]
In v12, we implemented a link between sale orders and contracts  in `product_contract` module.

We added several fields to sale order lines to be used at sale order confirmation in order to create a new contract.

From this fields there are `start_date` and `end_date` that @sbidoul and @hparfr proposed to depend on [`sale_start_end_dates`](https://github.com/OCA/sale-workflow/tree/12.0/sale_start_end_dates) module instead of adding them in `product_contract` module.

**Comment by sbidoul** [comment]
:+1:

**Comment by pedrobaeza** [comment]
OK for me too, although I don't like the plural in the other module name, but that's another question.
