### ISSUE TITLE
Contract: Cron picks wrong company properties in multi-company environment

### ISSUE THREAD

**Issue by svalaeys** [OCA/contract#410]
Hello,

I have recently installed contract on a multi-company environment.

Everything runs perfectly fine when creating invoices manually. However, when running the cron, the results are not as expected.

The cron is run as Odoobot. The problem happens when we go through the following method of the product class, which is called when onchange_product_id is called.:
@api.multi
def _get_product_accounts(self):
        return {
            'income': self.property_account_income_id or self.categ_id.property_account_income_categ_id,
            'expense': self.property_account_expense_id or self.categ_id.property_account_expense_categ_id
        }

It seems according to my debugging that the property that is being read is the property for the company that OdooBot belongs to (as far as I know the very first company created) as opposed to reading the property from the company the contract is for. So the account on the invoice line is not the one that's expected.

There is a simple solution to this: create as many crons as there are companies and use a company-specific acocunt for each cron. Sure it works, but it seems like a maintenance nightmare, having to create as many crons as there are companies, as well as potentially having to create users to run the crons (I usually don't create generic users per company). If I can avoid this, I'd love to.

Another iffy solution is to specify the account on the contract line and forget about on_change_product_id(). As far as I am concerned this is unacceptable as a change in the accounts on a product would require tracking every contract and changing the product there as well (I have hundreds of contracts).

Ideally, the perfect solution would be to "impersonnate" the company of the contract when generating the invoice. Is there a way to do that in Odoo?

Thank you very much for your input,

Stephane

**Comment by sbidoul** [comment]
That is definitely a bug that needs fixing. Which version are you using?

At first glance it should be enough to add a `with_context(force_company=contract.company_id.id)` when generating invoices.

cc/ @sbejaoui

**Comment by svalaeys** [comment]
I am using v12. Before submitting the issue I reproduced it on http://3394183-12-0-41d787.runbot1.odoo-community.org.

Thanks for the tip. I have never had the need to use force_company before, I am glad it exists. I will try this fix later today and submit a pull request if that does the job.

**Comment by svalaeys** [comment]
That did the trick. Will submit a pull request shortly.

**Comment by JordiADARIA** [comment]
Hi @svalaeys, did you do the PR? could you share it? im with the same problem, and we've thousands of not correctly automatically generated invoice lines every month... (we already tried the "multicron" creation but it seems not working anyway)

cc/ @sbejaoui

**Comment by svalaeys** [comment]
Hi Jordi,

 �

Have you updated your code recently? There were big changes in the last two months or so. Some of these changes made my fixes obsolete. To be honest, I have just made a couple of tests since I pulled the new code. It will run in production for the first time on April 1st.

 �

Let me know,

 �

Stephane

 �



 �

**Comment by JordiADARIA** [comment]
Hi Stephane, you were absolutely right, a lot of fixes were done in the last two months, and its already fixed, thanks a lot!

**Comment by sbejaoui** [comment]
Thank you all. I close this issue as it fixed in 12.0
