### ISSUE TITLE
Contract creation at sale order confimation

### ISSUE THREAD

**Issue by max3903** [OCA/contract#413]
Hello,

I am looking for a contract module that would:
* allow me to select a contract template on a sale order
* create the contract from the template when the sale order is confirmed

It's not clear the feature is available and in which module.

Thank you!

**Comment by max3903** [comment]
contract_sale only mentions providing access to salespersons...

**Comment by pedrobaeza** [comment]
product_contract is the one!

**Comment by sbejaoui** [comment]
maybe we need to have one module contract_sale.

**Comment by max3903** [comment]
@pedrobaeza Thank you!
