### ISSUE TITLE
[RFC] contract_sale_invoicing

### ISSUE THREAD

**Issue by max3903** [OCA/contract#415]
# Description

I have a scenario where the customer signs a contract to get assigned a pricelist. Later customer can order products and get invoiced based on the contract every month.

To achieve that, the contract will generate a draft invoice at the beginning of the month and all the sales orders of the month will update that invoice, until the month ends and the invoice is validated.

I would like to propose the following changes to `contract_sale_invoicing`:

## sale.order

- [x] Add a many2one field "Contract" (contract_id) to contract.contract
- [x] Filter the list of contracts based on the selected customer
- [ ] ~~When a sale order is confirmed, if the contract is set:~~
* ~~Find the draft invoice for that customer and contract~~
* ~~If you find one:~~
  * ~~For each sale order line~~
    * ~~Search for the same product in this invoice~~
    * ~~If you find one, update the quantity~~
    * ~~Otherwise add a new line~~
  * ~~Otherwise add a new invoice (default behavior)~~

## contract.contract

- [x] Extend _prepare_recurring_invoices_values to invoice the un-invoiced sales orders linked to the contract (not the analytic account). 1 invoice per contract with 1 line per product with the sum of the quantities from the sale orders lines.
- [x] Extend _compute_sale_order_count to include sales orders linked to the contract
- [x] Extend action_view_sales_orders to include sales orders linked to the contract

**Comment by pedrobaeza** [comment]
I don't think pre-generating the invoice and add lines is the right approach as it will keep a lot of useless documents during the period, plus you will need specific code for doing that. OK for adding the contract (but isn't this an agreement?) on the sale, but if you simply want to group orders by that contract/agreement, do that creating a module for aggregating sales orders by that field. I'm going to release this week a module that groups by delivery address that you can mimick for this purpose.

**Comment by max3903** [comment]
@pedrobaeza I don't want to group invoices. I want one invoice for all the sale orders of the month. That invoice will also allow me to track the consumption of the customer.

**Comment by pedrobaeza** [comment]
That's what I'm saying: group sales orders in one invoice (I have edited my previous comment for better clarity). For consumption I would put that information at contract level, not at invoice level.

**Comment by max3903** [comment]
@pedrobaeza Ok, I get you now. Let me check with my customer if this option works for him (piling up sales order during the month and generating one invoice at the end).

CC: @rto-odoo

**Comment by sbejaoui** [comment]
Take a look at [contract_sale_invoicing](https://github.com/OCA/contract/tree/12.0/contract_sale_invoicing), On each invoicing run, the system will check if there's any pending sales orders with same analyitic account and will append the lines to the invoice being generated (didn't test it but I think it's what you are looking for).

**Comment by pedrobaeza** [comment]
@sbejaoui it's not exactly the same, as the link is through analytic accounts.

**Comment by sbejaoui** [comment]
> @sbejaoui it's not exactly the same, as the link is through analytic accounts.

I believe that managing this use-case by a one analytic account (project) and many contracts and sale orders is better then a direct link between sale order and a contract.

**Comment by max3903** [comment]
@sbejaoui I will need to check if that solution is viable for my customer. 

Great inputs here. Thank you both!

**Comment by max3903** [comment]
Looks like all the contracts will have the same analytic account (the warehouse).

**Comment by pedrobaeza** [comment]
OK, then that module can serve.

**Comment by pedrobaeza** [comment]
Closing this as already solved.
