### ISSUE TITLE
[RFC] contract_fieldservice

### ISSUE THREAD

**Issue by max3903** [OCA/contract#416]
Depends on contract_sale and fieldservice_sale

This module allows you to set a service location on each line of the contract.

# Usage

* Go to Accounting > Customers > Contracts
* Create or select a contract
* Edit it to set the "Service To" on the lines
* Go to Sales
* Create or select a quotation
* Select the customer and contract to filter the list of "Service Location"

# Technical Specifications

## contract.line

- [x] Add a many2one field "Service To" (fsm_location_id) to fsm.location

## sale.order

- [x] Filter the list of service locations based on the contract

**Comment by murtuzasaleh** [comment]
#438
