### ISSUE TITLE
[ADD] contract_line_invoice_by_average

### ISSUE THREAD

**Issue by max3903** [OCA/contract#418]
Depends on account_invoice_pricelist, contract_sale and #415 

# Description

This module allows you to define products on a contract that needs to be invoiced by the average quantity instead of the sum.

For example, you may have a contract for 3 water dispensers and have 4 sales orders in a month for a total of 15 bottles of water. Your invoice would be:
- 3 water dispensers
- 5 bottles

# Configuration

* Go to Invoicing > Customers > Contracts
* Select or create a contract with a line
* Select the product (Dispenser), the quantity (3) and the products invoiced by average quantity (Bottle of water)

# Usage

* Go to Sales
* Create sales orders with the products invoiced by average quantity (bottle of water) and the same contract
* When the invoice is created, the quantity of the invoice line is not the sum of the sale order lines, but the average by the quantity on the contract line.

# Technical Specifications

## contract.line

- [ ] Add a many2many field "Products invoiced using average quantity" (products_invoiced_by_avg_ids) to product.product

## contract.contract

- [ ] Extend the method _recurring_create_invoice:
* to call super
* for each contract line where products_invoiced_by_avg_ids is set:
  * Build a table with the product invoiced using average quantity and the quantity of the contract line (vals['product_id'] = qty)
  * for each invoice
    * for each line
      * if the product from the invoice line matches one from the table
        * Divide the current quantity on the invoice line by the quantity in the table
        * Round
        * Update the quantity on the invoice line
        * Recompute the unit price using the price-list
* return the invoices

![Screenshot from 2019-11-15 12-58-40](https://user-images.githubusercontent.com/939952/68969940-bffc3380-07ab-11ea-9b1e-f87ba1a22544.png)

**Comment by pedrobaeza** [comment]
Do you know https://github.com/OCA/contract/tree/12.0/contract_variable_quantity? Maybe you can implement that average computation through it without the need of too much effort. See https://github.com/OCA/contract/tree/11.0/contract_variable_qty_timesheet as an example.

**Comment by max3903** [comment]
@pedrobaeza Thanks for the tip.

@murtuzasaleh @JayVora-SerpentCS Anyone working on this already or not?

**Comment by murtuzasaleh** [comment]
> @pedrobaeza Thanks for the tip.
> 
> @murtuzasaleh @JayVora-SerpentCS Anyone working on this already or not?

@max3903 We will start working on it.
