### ISSUE TITLE
Policy of changes for stable versions

### ISSUE THREAD

**Issue by mohamedhagag** [OCA/contract#419]
Dears,

I would like suggest a standard for changes in stable versions of odoo versions here.

Yesterday we lost our customer contracts due to a huge restructuring of contract module that rendered our working system unusable and caused our data corruption.

the change happened in the v12 branch which is stable and in production since at least a year.

So I suggest that these stable branches should not get such restructuring or huge changes in the data models and business objects.

changes to stable branches should only contain bug fixes and security patches.

Regards, 

@pedrobaeza

**Comment by pedrobaeza** [comment]
The policy is set: structural changes must be joined with migration scripts that adapt that changes, and that's the case for `contract` module: https://github.com/OCA/contract/tree/12.0/contract/migrations. I have successfully migrated customers (and our own instance) with it, so you have to check what have failed in your case, and put a specific issue about that.

**Comment by sbidoul** [comment]
> changes to stable branches should only contain bug fixes and security patches.

@mohamedhagag sorry to hear you have had issues with the update.

The update policy for OCA is not the same as Odoo. So feature and data model changes are expected on OCA branches. We try hard to have an upgrade path and migration scripts, however.

The version numbers of the addons should be a good indication of the importance of the changes.

As with any dependencies you include in your projects, it is an important good practice to freeze the versions you use in production, and make sure you analyze the difference when you install new versions.
