### ISSUE TITLE
[12.0] contract structural changes migration scripts issue

### ISSUE THREAD

**Issue by mohamedhagag** [OCA/contract#420]
when I try to upgrade contract module in v12 from 12.0.1.x to 12.0.2.4 which have structural changes in the contract object I get this error:

> Traceback (most recent call last):
  File "/NVME/odoo/ov12/odoo/odoo/odoo/service/server.py", line 1127, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/NVME/odoo/ov12/odoo/odoo/odoo/modules/registry.py", line 304, in init_models
    func()
  File "/NVME/odoo/ov12/odoo/odoo/odoo/fields.py", line 2129, in update_db_foreign_key
    new = process(model._cr, model._table, self.name, comodel._table, 'id', self.ondelete or 'set null')
  File "/NVME/odoo/ov12/odoo/odoo/odoo/tools/sql.py", line 185, in fix_foreign_key
    return add_foreign_key(cr, tablename1, columnname1, tablename2, columnname2, ondelete)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/tools/sql.py", line 158, in add_foreign_key
    cr.execute(query.format(tablename1, columnname1, tablename2, columnname2, ondelete))
  File "/NVME/odoo/ov12/odoo/odoo/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/NVME/odoo/ov12/odoo/odoo/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: insert or update on table "account_invoice" violates foreign key constraint "account_invoice_old_contract_id_fkey"
DETAIL:  Key (old_contract_id)=(181) is not present in table "contract_contract".

BTW, id 181 is there in the account_analytic_account table which is the old contract model.

help is more than appreciated.

**Comment by pedrobaeza** [comment]
The problem is that you have referenced an incorrect contract in that field. See if id 181 exists in your old BD. If not, you must set to null the invoices with that ID.

**Comment by sbejaoui** [comment]
Check if contract (id 181) has contract lines. If it's not the case, the migration script will ignore it. [See](https://github.com/OCA/contract/blob/12.0/contract/migrations/12.0.4.0.0/pre-migration.py#L99)

**Comment by mohamedhagag** [comment]
@pedrobaeza  it's failing on all invoices that's linked to contracts, and contract 181 exists
@sbejaoui contract 181 has below lines:

```
select id,analytic_account_id,name from account_analytic_invoice_line where analytic_account_id = 181;
 id  | analytic_account_id |            name             
-----+---------------------+-----------------------------
 217 |                 181 | اسم نطاق                   +
     |                     | اسم النطاق com - net - org 
(1 row)

```

**Comment by pedrobaeza** [comment]
Is the field `recurring_invoices` in account_analytic_account unmarked?

**Comment by mohamedhagag** [comment]
```
select id,recurring_invoices from account_analytic_account where id=181;
 id  | recurring_invoices 
-----+--------------------
 181 | t
(1 row)

```

**Comment by mohamedhagag** [comment]
I think that this line https://github.com/OCA/contract/blob/12.0/contract/migrations/12.0.4.0.0/pre-migration.py#L99 
should use the old name of the table instead of the new one `contract_line ` or we should ensure the rename of the table at this point.

**Comment by sbejaoui** [comment]
In the migration script, what do you get [here](https://github.com/OCA/contract/blob/12.0/contract/migrations/12.0.4.0.0/pre-migration.py#L89)

**Comment by mohamedhagag** [comment]
@sbejaoui it's the old name in current DB

```
\d account_analytic_invoice_line;
                                             Table "public.account_analytic_invoice_line"
       Column        |            Type             | Collation | Nullable |                          Default                          
---------------------+-----------------------------+-----------+----------+-----------------------------------------------------------
 id                  | integer                     |           | not null | nextval('account_analytic_invoice_line_id_seq'::regclass)
 analytic_account_id | integer                     |           | not null | 
 create_uid          | integer                     |           |          | 
 name                | text                        |           | not null | 
 uom_id              | integer                     |           | not null | 
 specific_price      | double precision            |           |          | 
 write_uid           | integer                     |           |          | 
 discount            | numeric                     |           |          | 
 write_date          | timestamp without time zone |           |          | 
 create_date         | timestamp without time zone |           |          | 
 quantity            | double precision            |           | not null | 
 product_id          | integer                     |           | not null | 
 sequence            | integer                     |           |          | 
 automatic_price     | boolean                     |           |          | 
Indexes:
    "account_analytic_invoice_line_pkey" PRIMARY KEY, btree (id)
Foreign-key constraints:
    "account_analytic_invoice_line_analytic_account_id_fkey" FOREIGN KEY (analytic_account_id) REFERENCES account_analytic_account(id) ON DELETE CASCADE
    "account_analytic_invoice_line_create_uid_fkey" FOREIGN KEY (create_uid) REFERENCES res_users(id) ON DELETE SET NULL
    "account_analytic_invoice_line_product_id_fkey" FOREIGN KEY (product_id) REFERENCES product_product(id) ON DELETE SET NULL
    "account_analytic_invoice_line_uom_id_fkey" FOREIGN KEY (uom_id) REFERENCES uom_uom(id) ON DELETE SET NULL
    "account_analytic_invoice_line_write_uid_fkey" FOREIGN KEY (write_uid) REFERENCES res_users(id) ON DELETE SET NULL
Referenced by:
    TABLE "account_analytic_invoice_line_account_analytic_tag_rel" CONSTRAINT "account_analytic_invoice_line_account_analytic_invoice_lin_fkey" FOREIGN KEY (account_analytic_invoice_line_id) REFERENCES account_analytic_invoice_line(id) ON DELETE CASCADE

```

**Comment by pedrobaeza** [comment]
> I think that this line https://github.com/OCA/contract/blob/12.0/contract/migrations/12.0.4.0.0/pre-migration.py#L99 should use the old name of the table instead of the new one contract_line or we should ensure the rename of the table at this point.

No, it's renamed previously.

**Comment by sbejaoui** [comment]
try to run the migration without filtering on contract

replace this 

https://github.com/OCA/contract/blob/00d71f96f5b47efb89e6f4a45394bd8202284c35/contract/migrations/12.0.4.0.0/pre-migration.py#L95-L103

by this

```python
openupgrade.logged_query(
        cr, sql.SQL("""
        INSERT INTO contract_contract
        SELECT * FROM account_analytic_account
        WHERE partner_id IS NOT NULL
        """),
    )
```

**Comment by mohamedhagag** [comment]
OK, it went fine now

The problem solved by following this upgrade path:

1- upgrade base_comment_template
2- upgrade hr_timesheet_sheet
.... upgrade any module that depends on contract (this may go into loop of circular deps)
3- upgrade contract

and this shows how complex is the system if we need to restructure a business object like what happened here that's used by many other modules. 

Please review the policy of changes and consider these common cases of complexity.

Regards,

**Comment by mohamedhagag** [comment]
Thank you @sbejaoui @pedrobaeza for your great help

I will close this now.

**Comment by mohamedhagag** [comment]
BTW the migration didn't create any contract_line although it didn't show any error.

only contract_contract s created

**Comment by mohamedhagag** [comment]
@sbejaoui I will try your fix now

**Comment by mohamedhagag** [comment]
it still does not fix the issue

I have to work with the DB manually to handle many issues

**Comment by mgielissen** [comment]
I had the same problem, my solution was to delete the analytic account related to the contract.
