### ISSUE TITLE
[12.0] agreement_maintenance: Travis broken

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/contract#425]
The problem is depicted here:

https://travis-ci.org/OCA/contract/jobs/615318278#L1420

**Comment by max3903** [comment]
Interesting, field is there in the view:
https://github.com/odoo/odoo/blob/12.0/addons/maintenance/views/maintenance_views.xml#L352
https://github.com/OCA/OCB/blob/12.0/addons/maintenance/views/maintenance_views.xml#L352

**Comment by pedrobaeza** [comment]
Thanks!
