### ISSUE TITLE
[CONTRACT] The recurring rule type monthly-last-day

### ISSUE THREAD

**Issue by sbejaoui** [OCA/contract#426]
Hi, 

On a contract line there are two fields that define how to compute the next invoice date.
1.  `recurring_rule_type`: the invoicing period: week, month..
2.  `recurring_invoicing_type`: the invoicing policy: pre-paid or post-paid

But there is one `recurring_rule_type` option that cause a problem in this logic. it's the `monthlylastday` which mix in the same notion the invoicing period and policy.

Managing this option increased code complexity by:
* the need to have a separate logic for computing the next invoice date 
* the need to have a separate logic for computing the last invoiced date 
* making the `recurring_invoicing_type` useless when this option is selected

I propose to simplify all this by a small change for the post-paid case:
- The next invoice date is the last day in the period and not the first date of the next period.

example:
* contract line starts 01/11, monthly post-paid
   * `recurring_next_date` --> 30/11
* after invoicing the first period
   * `invoice_date` --> 30/11
   * `last_date_invoiced` --> 30/11
   * `recurring_next_date` --> 31/12

cc: @gva-acsone, @sbidoul , @pedrobaeza

**Comment by pedrobaeza** [comment]
@carlosdauden what do you think about this that you know post-paid cases?

**Comment by pedrobaeza** [comment]
The idea behind `monthlylastday` was to set the invoicing day, but without altering the invoiced period. For example, you start the contract on 14/01. With this option, you invoice on 31/01, but taking the period 14/01 to 13/02. Maybe we should set a third field for setting the invoice date independently from the rest?

**Comment by sbejaoui** [comment]
I can't imagine the invoice date completely independent from the invoicing period. 

When a user select an option from the field `recurring_invoicing_type` (pre-paid or post-paid), he select whether he will invoice his customer at the first day or the last day of the period.

There was a PR that proposed to have field to shift the invoice date from its original value. We can add it to this scoop if we really need to have a different invoice date then :

- The default behavior is:
   - pre-paid option make the invoice date the first day of the period
      - the invoicing period is [the last day invoiced + one day , next invoice date + one period]
   - post-paid option make the invoice date the last date of the period
      - the invoicing period is [the last day invoiced + one day , next invoice date]
- If a shift is set:
   - the invoicing period is the same
   - the invoice is created on the original invoice date
   - the invoice date = invoice date + shift

**Comment by pedrobaeza** [comment]
What do you think about this proposal, @carlosdauden? I agree in principle with shift option, but not sure if the disconnection of the invoicing period with the invoice date is a real need.

**Comment by Eusebius1920** [comment]
I have a case where the payment is a mixture between post-paid and pre-paid. The invoice should be generated in the middle of the invoicing period ("mid-paid"). This is a compromise to the customers between the two extremes of pre-paid (customer has to go full advance) and post-paid (company has to go full advance)

As I read above this would be possible with a shift, correct? (the invoiced would created in advance though, right?) Another idea would be to add the shift to the invoicing period? So you can select pre-paid, but shift the shown invoicing period in the invoice?

**Comment by babatoko** [comment]
+1, have got the same use case than the one lastly exposed.

**Comment by sbidoul** [comment]
@Eusebius1920 @babatoko the offset field is already present here
https://github.com/OCA/contract/blob/a52e1fe46d60551bbb7eb08ae6785aca25fffc5b/contract/models/abstract_contract_line.py#L79-L86

It is currently a computed field with only 1 day and 0 as possible values.

But if you make it a user-modifiable field, everything else should continue to work.

The only "difficulty" is to provide a migration path (migration script, and proper default values so existing users are not too surprised by the change).

**Comment by sbidoul** [comment]
BTW, @sbejaoui can we close this issue, and perhaps open new more focused issues for specific enhancements such as the user modifiable offset field?

**Comment by sbejaoui** [comment]
resolved with #434
