### ISSUE TITLE
[CONTRACT] - Pre-paid mode, invoice the first of each month except for the first period

### ISSUE THREAD

**Issue by sbejaoui** [OCA/contract#428]
Hi,

We have a use case that the current version of the contract module can't handle. 

For a contract line that starts at 07/11 in a pre-paid mode, the user would like to invoice his customer the first of each month except for the first period that it will be at the 07/11.

To resolve this use case, I propose to add a new field that will be shown to the user only if the last date invoiced is not set (a contract line that was never invoiced)

This field will ask the user about the end date of the first invoicing period and will be automatically set to : `date_start + the invoicing period - 1`.

Let see what this gives with our use-case:

- start date: 07/11
- pre-paid
- montly
- next invoicing date: 07/11
- last date invoiced: None
- first period invoice to date
   - Visible to user
   - set to 06/12

1- If the user don't change the **first period invoice to date** and create the first invoice --> nothing changes comparing to the current version.
2- If the the user set the **first period invoice to date** to 30/11 and create the first invoice:
  -  last date invoiced: 30/11
  - invoice created for the period 07/11 to 30/11
  - next invoicing date: 01/12
  - first period invoice to date
    - not visible to user

What do you think about this change?

cc/ @gva-acsone, @sbidoul , @pedrobaeza

**Comment by pedrobaeza** [comment]
What about the proposal of the third field I have done in the other issue? Having the invoicing date on the first of the month, you take the maximum of start date/invoicing date for setting that date.

**Comment by sbidoul** [comment]
#434 now has the concept of offset (to offset the invoice date from the beginning/end of the period).
The offset is currently hard-coded for backward-compatibility (0 for pre-paid and monthlylastday, 1 otherwise). The code is now simple enough that we can add a field so the user can adjust the offset. This could be part of an additional commit in #434.
