### ISSUE TITLE
[12.0][BUG][product_contract] Unit price of product is not propagated to the lines

### ISSUE THREAD

**Issue by rafaelbn** [OCA/contract#435]
- Create a product and set a price

1.
- Select the product in a contract template
- [BUG1] The price of the product it's not propagated to the contract template line

2.
- Select the product in a contract
- [BUG2] The price of the product it's not propagated to the contract line

![2019-12-12_8-22-00](https://user-images.githubusercontent.com/8736623/70692249-344ac980-1cbb-11ea-8476-52027a1c504c.png)

**Comment by pedrobaeza** [comment]
That's because you haven't put the pricelist.

**Comment by rafaelbn** [comment]
Because, it is not needed. Pricelist are not used in general and not pricelist are created.

I don't thin this module should force to use pricelist. Isn't it @sbidoul @pedrobaeza @sbejaoui ?

![2019-12-12_9-31-48](https://user-images.githubusercontent.com/8736623/70695616-6d3a6c80-1cc2-11ea-89f1-12d414901f2b.png)

**Comment by pedrobaeza** [comment]
Right now is enforced if you want automatic prices.

**Comment by rafaelbn** [comment]
Right now "automatic prices" doesn't work at all.

**Comment by pedrobaeza** [comment]
Yes if you put the pricelist.
