### ISSUE TITLE
[12.0][BUG][product_contract] Contract are created with double lines than the contract template

### ISSUE THREAD

**Issue by rafaelbn** [OCA/contract#436]
1. Create a contract template
![2019-12-12_9-00-50](https://user-images.githubusercontent.com/8736623/70693924-b7b9ea00-1cbe-11ea-98e9-7dcc4ac9f66e.png)

2. Create a product for the previous template
![2019-12-12_9-06-19](https://user-images.githubusercontent.com/8736623/70693935-bc7e9e00-1cbe-11ea-9860-526e24f3bb59.png)

3. Create a sale order with the product of (2)
![2019-12-12_9-00-14](https://user-images.githubusercontent.com/8736623/70693970-d3bd8b80-1cbe-11ea-90d3-cd37cf3f0c5b.png)

4. [BUG] Confirm the sale order and check the contract created with double lines (it look like from the product configuration + contract template configuratoin
![2019-12-12_9-00-38](https://user-images.githubusercontent.com/8736623/70694086-13847300-1cbf-11ea-82fd-635521f6a94d.png)

**Comment by rafaelbn** [comment]
@sbejaoui @sbidoul @pedrobaeza 

I comment this last year in the first movements to change all the logic.

I comment here because FIXING this BUG will imply delete that fields.

![2019-12-12_9-16-24](https://user-images.githubusercontent.com/8736623/70694903-e20ca700-1cc0-11ea-8ed4-e1aea2ba45bc.png)

**Comment by sbejaoui** [comment]
Hi @rafaelbn ,

A contract template has multiple usage in the `product_contract` module:

- At sale order confirmation, odoo will group sale lines with the same contract template and create a contract for each one of them.
- When creating the contract, odoo will initialize it with the contract template value. 

If your contract template has the same products as the sale order, you probably don't need to use this flow. you can create the contract manually and select the template.

The `product_contract` module purpose is to assure the negotiation phase between the sale person and the customer that can't be handled with the contract object. 

The salesperson create his quotation with subscription products then when he get the customer confirmation he get his contract by the simple confirmation of the quote. 

For some use cases, there are additional services that are added automatically to the contract without being in the sale order. in this case they can be added to the contract template.

At the end of the day, the contract will contain lines coming from the SO and lines coming from the contract template.

**Comment by sbejaoui** [comment]
> @sbejaoui @sbidoul @pedrobaeza
> 
> I comment this last year in the first movements to change all the logic.
> 
> I comment here because FIXING this BUG will imply delete that fields.
> 
> ![2019-12-12_9-16-24](https://user-images.githubusercontent.com/8736623/70694903-e20ca700-1cc0-11ea-8ed4-e1aea2ba45bc.png)

Those field are used as default values when filling a contract or a sale order. This help the company to set it default invoicing strategy per product.

I don't get how we can achieve this with the contract templates

**Comment by rafaelbn** [comment]
Hello @sbejaoui ,

Well, the main concern (I said in the big change) it that I think (and our customers think) that the recurrence should be in the "Contract template" (now "Contract template lines") and not in the product.

You want templates like: "Monthly work", "Quarter work", "Yearly work" but the product is the **same**. Because you sell the same with different re-currencies.

All that fields in the product.template should be in the "Contract template lines" after your big change.

It has no sense to have n-product per n-recurrences :cry: 

With this functional approach you are giving a lot of height to the product and the contract templates are mainly useless.

Another argument is that if a user follow the steps and get that, obviously "the software" is not well thought.

We should see the functionality from the user point of view, should be intuitive (to be used without explanation), should be user friendly and a general approach (valid for lots of different customers)

Any case, up to you closing this issue as PSC.

**Comment by sbejaoui** [comment]
The `product_contract` module is almost developed from scratch in V12, so all this is new and not a change. 

In your case, the contract template is used like a "phantom bill of material". At sale order confirmation, the product is not added to the contract, only the lines in the related contract template.

I think this can be an enhancement: add a flag to the product template to decide to add it or not to the contract at the SO confirmation.

**Comment by rafaelbn** [comment]
Functionally the best way is moving to `subscriptions` in Odoo EE in this moment. My concern is that I didn't have time to review deeply your work. If you test contract, product_contract and contract_sale in Odoo v10 en OCA, it's not needed at all recurrence in the product.

You need recurrence in the product because you need recurrence in the contract lines.

We @sbejaoui work with customers which comes form OpenERP 5 and they have been migrated from  version to version every year. And now migrating our customers with contract form previous versions to the new one with recurrence by line is a headache and really big work.

We shouldn't never agree in changing the main simple mechanism. That should be done in a separate module. That my fault.

Today I'm really tired and after some hours of review my head is broken. So I close this. :smile: 

Tomorrow we will see, we need recurrence in the contract and not in the contract lines, and we need recurrence in the contract templates and not in the product, as v10. And as last 5 years. That's my conclusion.

**Comment by sbidoul** [comment]
> we need recurrence in the contract and not in the contract lines

That part should be solvable relatively easily at the UI level by adding computed field with inverse on the contract and an option to enforce the same recurrence option on lines. Recurrence options will still be stored on lines but the user can enter them in the contract (and we can probably even hide them on the contract lines if the flag "same recurrence on all lines" is enabled on the contract).
