### ISSUE TITLE
[12.0] [BUG] when calling `Generate Recurring Invoices from Contracts` Scheduled Actions

### ISSUE THREAD

**Issue by nikul-serpentcs** [OCA/contract#440]
When I created many Contracts and Call  **Generate Recurring Invoices from Contracts** Scheduled Actions. Got singleton Error Like this.

![Issues---](https://user-images.githubusercontent.com/17664321/70990855-652c6380-20ec-11ea-8c86-0c43b110d3f4.png)

**Comment by sbejaoui** [comment]
the bug is in [`contract_sale_invoicing`](https://github.com/OCA/contract/blob/12.0/contract_sale_invoicing/models/contract.py#L19).

the `_recurring_create_invoice` should be rewrite in multi mode

**Comment by nikul-serpentcs** [comment]
@sbejaoui I solved bug
```
    @api.multi
    def _recurring_create_invoice(self, date_ref=False):
        invoices = super()._recurring_create_invoice(date_ref)
        for rec in self:
            if not rec.invoicing_sales:
                return invoices
            sales = self.env['sale.order'].search([
                ('analytic_account_id', '=', rec.group_id.id),
                ('partner_invoice_id', 'child_of',
                 rec.partner_id.commercial_partner_id.ids),
                ('invoice_status', '=', 'to invoice'),
                ('date_order', '<=',
                 '{} 23:59:59'.format(rec.recurring_next_date)),
            ])
            if sales:
                invoice_ids = sales.action_invoice_create()
                invoices |= self.env['account.invoice'].browse(invoice_ids)[:1]
```

**Comment by pedrobaeza** [comment]
Please do a PR.

**Comment by nikul-serpentcs** [comment]
> Please do a PR.

@pedrobaeza  Done

**Comment by AaronHForgeFlow** [comment]
Where is the PR?

**Comment by AaronHForgeFlow** [comment]
> Where is the PR?

https://github.com/OCA/contract/pull/437 :)

**Comment by AaronHForgeFlow** [comment]
I'd rather prefer to do the fix in a separate PR than that one, because that one includes some bigger changes in that module.

**Comment by nikul-serpentcs** [comment]
Not Needed @AaronHForgeFlow, Because of a little bit changed Flow.
That's why we covered this issue in Open PR https://github.com/OCA/contract/pull/437.

**Comment by pedrobaeza** [comment]
For quicker reaction, it's better to split the fix from other improvements. Not doing so, people will be more reluctant to merge everything "in pack".

**Comment by pedrobaeza** [comment]
Closing as there's a PR in progress.
