### ISSUE TITLE
[RFC] website_portal_contract: Website Contract Management

### ISSUE THREAD

**Issue by lasley** [OCA/contract#45]
This module will provide website views for customer management of their existing contracts. 

It will add a new field `website_template_id` to the `account.analytic.contract` model (and subsequently the `account.analytic.account` model). This field will act in the same way that the quote template works for website sales. A default template will be provided.

It will provide a new section in the website `My Account`, similar to the existing `Your Quotes`, `Your Orders`, etc & will be called `Your Contracts`.

In the `Your Contracts` listing, the following fields will be displayed in the table:

* Display Name
* Debit
* Credit
* Balance

Clicking a contract in the listing will take you to the website template associated with that contract.

**Comment by rafaelbn** [comment]
It's more website_portal_contract, isn't it?

**Comment by lasley** [comment]
@rafaelbn - Yup that's a better name for sure

**Comment by dreispt** [comment]
Add to the wishlist a "Your Issues" feature, and "Open an Issue"

**Comment by pedrobaeza** [comment]
Isn't that already on website_issue?

**Comment by dreispt** [comment]
You're probably right. Ignore that then.

**Comment by vonpupp** [comment]
Using a module such as this would it be possible to automatically charge a credit card? Such as a subscription monthly payment?

**Comment by lasley** [comment]
@vonpupp - That is not within scope right now, but autopay is part of my long-term plans. That will likely be in a separate module though in order to allow for usage outside of this context.

**Comment by vonpupp** [comment]
Great @lasley. I am not aware of any module right now that allows recurrent payments. Perhaps the closest might be the [memberships] module. I think it would be very nice to have something similar to the Odoo enterprise feature [subscriptions].

There is also an effort on the [donation] module to achieve recurrent payments. Wouldn't it be possible to create some sort of "fit all" recurrent payment module that integrates with contracts, memberships and donations?

[memberships]: https://github.com/OCA/vertical-association/issues/19
[subscriptions]: https://www.odoo.com/page/subscriptions
[donation]: https://github.com/OCA/donation/issues/22

**Comment by pedrobaeza** [comment]
AFAIK Odoo enterprise doesn't handle either automatic recurrent payment. And this is very closely related with payment gateways (Paypal and so on) to allow this option.

**Comment by vonpupp** [comment]
I have not tried this myself but Fabien [stated] that it is supported on the Enterprise version @pedrobaeza. I believe this feature would be very important and would boost Odoo adoption IMHO.

If I have some help and somebody to count on to provide some guidance I would gladly help. As I said I am a beginner with Odoo, so patience is important :)

[stated]: https://www.odoo.com/forum/help-1/question/how-to-process-recurring-payments-donations-116039

**Comment by pedrobaeza** [comment]
OK, I see, but he is saying that it works only with Ingenico and Stripe payment gateways, and in Enterprise version. There are 2 ways to do it:

1) Automatically making the charge every period, which has to be supported by payment gateway, and that you are authorized to make it (in Spain it's very difficult to get this authorization).
2) Sending a reminder each period with a link to make the payment.

Second is more feasible, but doesn't guarantee the payment.

**Comment by lasley** [comment]
v10 added a lot of server to server interaction with some of the payment gateways, so this did become a bit more feasible from the tech end of things - but there is still no unified interface, so each automation would need to be created independently as Odoo SA has done for Stripe & Ingenico.

The mental plan was to create a `base_payment_auto` module to provide the base interface, then a `payment_authorize_auto` to cover the scope of my needs. In the US we can charge whatever the hell we want, whenever we want; so I'm not worried about legalities. The downside are chargebacks, but that's a merchant consideration IMO.

I can create an RFC for this if you guys want - it's a only rough idea at this point though, and is pretty far off in our dev schedule.

**Comment by pedrobaeza** [comment]
For now I don't have that need, so you can still retain it for more time to improve it if you want.

**Comment by vonpupp** [comment]
Great proposal @lasley.

Having a request made by email automatically (i.e: monthly) would be also something feasible that would indeed be better than nothing, perhaps both of these proposals would cover all the needs of recurrent payments.

For instance in Brazil we have a quite common payment method called "boleto", which is some sort of payment order with a bar code that the customer pays directly at the bank / ATM or phone. If the donors could receive these boletos each month by email it would be awesome.

I am still trying to integrate this on v10 without the need of the localization for the sake of simplicity. The NGO I am helping need more the financial part rather than the accounting part, so the simpler the better.

**Comment by pedrobaeza** [comment]
This is already implemented, isn't it?

**Comment by lasley** [comment]
Indeed it is, I guess we just forgot to link to and close the RFC!

https://github.com/OCA/contract/tree/10.0/website_portal_contract
