### ISSUE TITLE
[Enhancement] - Contract Resiliation

### ISSUE THREAD

**Issue by sbejaoui** [OCA/contract#458]
Hi, 

In some cases, customer ask to resiliate his contract and all services sold within.

With the current version, it's possible to achieve this by stopping all contract line at the resiliation date.

what is missing is: 
*  the possibility to highlight that was a contract resiliation
*  prevent users from resuming the contract.

I propose to:
*  Add a new user group that give the ability to resilite a contract 
*  Add a new button to the contract **Resiliate Contract**  that open a wizard and ask the user to set:
   *  Resiliation date
   *  Resiliation reason
*  The resiliation action will call the stop action at the resiliation date for each contract line
*  Add a Boolean field to identify a resiliated contract
*  A resiliated contract can't be edited
*  Add the mention **Resiliated** to the contract report
*  The same user group can cancel a resiliation and reopen the contract. 

cc/ @gva-acsone, @sbidoul , @pedrobaeza

**Comment by dreispt** [comment]
With `resiliation` do we mean `termination`?
