### ISSUE TITLE
BUG expected singleton

### ISSUE THREAD

**Issue by javierjcf** [OCA/contract#460]
https://github.com/OCA/contract/blob/693fe5a3cce2712d9f5696713abe1eb7f41a4fb3/contract_sale_invoicing/models/contract.py#L19

This is a bug. When cron calls this method, there are a lot of contracts in self, so wqe get a expected singleton error. We need put a for bucle here

**Comment by pedrobaeza** [comment]
Duplicated of #440 and fixed in #442
