### ISSUE TITLE
Bug api multi with cron

### ISSUE THREAD

**Issue by javierjcf** [OCA/contract#461]
https://github.com/OCA/contract/blob/693fe5a3cce2712d9f5696713abe1eb7f41a4fb3/contract/models/contract.py#L438.

If you do the action for more than one contratr it will raise a singleton error.

**Comment by pedrobaeza** [comment]
AFAIK, that one is only triggered manually.

**Comment by javierjcf** [comment]
Yes it is,
But if you try to do a server action in order to invoice more than one from the list view, you can t use it.
I think it would be a improve to respect the api multi and avoid the singleton error, but you are right, this method can only be called from a single button.

**Comment by pedrobaeza** [comment]
If you do a server action call the one with leading `_` or put the loop and call record per record. The only improvement I see is to add an explicit `self.ensure_one()`.

**Comment by javierjcf** [comment]
Thanks pedro, this issue can be closed.
I add the loop, because i need the message post of the method without the _.

**Comment by pedrobaeza** [comment]
OK.
