### ISSUE TITLE
Logo SVG (Legal Agreements)

### ISSUE THREAD

**Issue by marcelsavegnago** [OCA/contract#463]
Hi, 

Does anyone have the logo (SVG) of the Legal Agreements module?

**Comment by marcelsavegnago** [comment]
The current icon is smaller than the other icons when using the web_responsive module. If nobody has the SVG file, I propose a new logo. What do you think ?

![icon](https://user-images.githubusercontent.com/3595132/74282011-330b3c80-4cfe-11ea-8f65-55a3f09b83c2.png)


[icon.zip](https://github.com/OCA/contract/files/4188562/icon.zip)

**Comment by marcelsavegnago** [comment]
@ygol Do you have the agreement_legal module logo vector?

**Comment by ygol** [comment]
I don't have the vector. The current icon comes from the "agreement" module in v11.

**Comment by marcelsavegnago** [comment]
> I don't have the vector. The current icon comes from the "agreement" module in v11.

I saw it now ... but it doesn't have the vector either.

**Comment by marcelsavegnago** [comment]
@ygol Do you believe that it is worth opening a PR to replace the Icon? I understand that it is only visual but it makes a small difference ?

![image](https://user-images.githubusercontent.com/3595132/74285846-69988580-4d05-11ea-8a0d-b4d64f9d69d0.png)

![image](https://user-images.githubusercontent.com/3595132/74285891-7917ce80-4d05-11ea-9f75-0e6dcf0e3880.png)

**Comment by ygol** [comment]
On runbot it is not showing smaller:
http://3407763-12-0-2eb377.runbot2.odoo-community.org/web#action=32&model=ir.module.module&view_type=kanban&menu_id=5
![image](https://user-images.githubusercontent.com/2945174/74316953-27ae2480-4d83-11ea-9e86-582efbb64d07.png)

**Comment by marcelsavegnago** [comment]
> On runbot it is not showing smaller: http://3407763-12-0-2eb377.runbot2.odoo-community.org/web#action=32&model=ir.module.module&view_type=kanban&menu_id=5 ![image](https://user-images.githubusercontent.com/2945174/74316953-27ae2480-4d83-11ea-9e86-582efbb64d07.png)

In this case you are looking at the list of applications. Install the Web Responsive module and see that in this case the icon is impacted due to the image resolution. See the print screen below.

![image](https://user-images.githubusercontent.com/3595132/74365230-660c0980-4dac-11ea-9672-bfcb6e40e351.png)

**Comment by ygol** [comment]
I'm fine with your new icon 👍
