### ISSUE TITLE
[12.0][contract][product_contract] Is contract module multi-company?

### ISSUE THREAD

**Issue by rafaelbn** [OCA/contract#464]
Hello,

I test the module in multi-company enviroment and it doesn't look like multi-company is supported when you add `product_contract`

- In Odoo products are multi-company, this means that you can use 1 product for n companies
- Contract templates are not multi-company, this means 1 "contract template" per company.

In a real environment with 30 products for contract, when you stablish a `contract template` then **the product becomes single-company** :cry: 

![2020-02-10_21-14-25](https://user-images.githubusercontent.com/8736623/74186210-74daab00-4c4a-11ea-8335-ca91a7708d18.png)

**Comment by rafaelbn** [comment]
@sbejaoui  @pedrobaeza @ernestotejeda 

This field should be not required. All products available for all companies and all contract templates too.

https://github.com/OCA/contract/blob/12.0/contract/models/abstract_contract.py#L44

**Comment by pedrobaeza** [comment]
Not making it required will require several integrity checks, and convert some fields like `journal_id` to company_dependent, which doesn't worth IMO.

**Comment by sbejaoui** [comment]
Hi @rafaelbn ,

We are using contract modules in a multi-company setup and I can say that it works overall.

In our case, each company have its own product catalog. For this reason we didn't face this issue. I think with this PR #465 the issue is fixed

**Comment by sbejaoui** [comment]
(I updated my comment)

Hi @rafaelbn ,

We are using contract modules in a multi-company setup and I can say that it works overall.

In our case, when companies share the same product catalog we create shareable contract template (contact template not related to any company).

**Comment by sbejaoui** [comment]
Hi @rafaelbn ,

We are using the contract modules in a multi-company setup and we faced this situation.

We needed to share the same product catalog between 3 companies from a total of 5 companies using contracts.

We created a virtual parent company for this three company and affected the product catalog and their contract template to it.

The idea to make the contract template company dependent can work (#465) but I think you must expect a much more hidden work to achieve it, like @pedrobaeza mentionned

**Comment by rafaelbn** [comment]
Thanks @sbejaoui for you explanation. I am very grateful.

My conclusion is that contract and product contract are not OCA generic modules as don't help the most of the simple use cases.

- Create virtual parent company is a really amazing workaround :astonished: 

I'm sad about this really.

Indeed when explaining to new customers in v12 contract, the ask me "I don't know If I  have understand it it looks complicated" and them my face turns a explain this situation about "this can happens in open source and I agree with you".

I don't know how to manage this now with happy customers from older versions to v12.
