### ISSUE TITLE
[11.0] contract_price_revision is still calculating lines that are not valid anymore

### ISSUE THREAD

**Issue by yung-wang** [OCA/contract#467]
In a contract you have 2 lines.
1 - Valid from 01/01/2018 till 12/31/2018
2 - Valid from 01/01/2019 till -----

When you run the revision tool and add 10%, you would expect only the valid line would be updated. But the module updates both lines.

Steps to reproduce:
--- create a contract with 2 lines with different start and end dates
![image](https://user-images.githubusercontent.com/30628967/74438432-72ef3280-4e6a-11ea-9070-6fada2dd6f2d.png)

--- Run the revision for this contract and add 10%
![image](https://user-images.githubusercontent.com/30628967/74438511-a631c180-4e6a-11ea-866f-645145802b60.png)

--- Check the contract, and you will see that both lines are revised.
![image](https://user-images.githubusercontent.com/30628967/74438585-ceb9bb80-4e6a-11ea-9210-8522bf8339db.png)

I would expect that only the valid line to be revised.

**Comment by pedrobaeza** [comment]
Fixed already
