### ISSUE TITLE
[12.0][contract] If contract_contract hasn't the same (or more) fields, the function breaks

### ISSUE THREAD

**Issue by oscars8a** [OCA/contract#476]
https://github.com/OCA/contract/blob/23817b0141b05670bad48f003f11a7fe13d2a354/contract/models/contract.py#L214

Hi everybody,

In this line, if contract_contract model hasn't the same, or more, fields than contract_template model, the function breaks.

I don't know if this is a issue or a limitation. "Contract model must have at least the same fields than Contract Template model."

Thanks a lot.

**Comment by pedrobaeza** [comment]
If you don't want to be synced, just add them in

https://github.com/OCA/contract/blob/23817b0141b05670bad48f003f11a7fe13d2a354/contract/models/abstract_contract.py#L17

**Comment by oscars8a** [comment]
> If you don't want to be synced, just add them in
> 
> https://github.com/OCA/contract/blob/23817b0141b05670bad48f003f11a7fe13d2a354/contract/models/abstract_contract.py#L17

Very helpful @pedrobaeza, thanks for everything and sorry for the time.
