### ISSUE TITLE
column "contract_id" referenced in foreign key constraint does not exist

### ISSUE THREAD

**Issue by qzmxs** [OCA/contract#478]
module: contract
version: 12.0
column "contract_id" referenced in foreign key constraint does not exist
**Steps to reproduce**
- ...
![image](https://user-images.githubusercontent.com/55458897/75120274-4e465680-56c5-11ea-9a9f-0b6142f33ec2.png)
![image](https://user-images.githubusercontent.com/55458897/75120281-674f0780-56c5-11ea-9ed4-a1d8e53cfbb8.png)
![image](https://user-images.githubusercontent.com/55458897/75120289-7930aa80-56c5-11ea-89eb-af8578c0c99e.png)

**Current behavior**

**Expected behavior**

**Comment by pedrobaeza** [comment]
Sorry, but that's not the steps to reproduce the problem. You are installing the module in some kind of contaminated DB or a bad deployment, and thus it doesn't work. You can click on the try me on runbot button to see that the module works perfectly in a clean environment. Try that in your local as well.
