### ISSUE TITLE
[RFC] "Recurring Contracts" app

### ISSUE THREAD

**Issue by dreispt** [OCA/contract#482]
Would you agree on promoting `contract`to a top level App?
We would need to create the top level menu, security groups, and the Apps specific menus.

**Comment by pedrobaeza** [comment]
Not sure of this... we already have it under "Invoicing" section, which is very suitable, and an extension for sales. Isolating it will complicate permissions.

**Comment by dreispt** [comment]
It will stand out as an alternative to Subscriptions.
And will allow to have a proper configuration section proposing the extra features in the repo.
Leaving a few redundant menus under "Invoicing" is not an issue at all.

**Comment by pedrobaeza** [comment]
The alternative is real and more powerful. We can put it as application, but not the new menu and the rest IMO.

**Comment by dreispt** [comment]
What would be needed for a Recurring Contracts App top menu, similar to Subscriptions, to make sense?

**Comment by pedrobaeza** [comment]
@sbidoul @sbejaoui please comment what are your thoughts on this or let's close it. For me, putting `application=True` is OK. Adding a top menu, maybe if we still keep the others (or we should replicate also menus for customers/suppliers with recurring invoicing, and even recurring invoices). Isolating permissions is mostly a no due to the side effects + the change in the behavior.

**Comment by sbidoul** [comment]
Hi, I've not given much thought to that. Why not a top level menu, it could make sense. Do you have a proposal @dreispt ? Noting it's both for customer and supplier invoices. Regarding permissions, I've no idea... I would need to see a design or PR to think about it.

**Comment by babatoko** [comment]
If I can give my thoughts, recursive invoice is just the result of a process and not an application.

It could become an app when it will be possible to manage recurrency from the quote to the generate invoice and throughout activities or tasks.
