### ISSUE TITLE
Create recurring contract from sales order

### ISSUE THREAD

**Issue by babatoko** [OCA/contract#484]
Hi I'm wondering if it's possible to trigger the creation of a recurring contract from a sales order (with data copy from sales order). If yes how to do that. If not, it would make sense to me at least.

Cheers,

Babatoko

**Comment by pedrobaeza** [comment]
This issue tracker is for issues in the code, not for questions.

Any way, check `product_contract` module for that, and the rest of the questions must be done on the Odoo forums.

**Comment by babatoko** [comment]
Thanks for replying.

I know that and use it as it is and I feel inconfortable with all things done underground.

I think it could be more efficient to have a button create contract just next to create invoice and trigger a wizard to set the contract.

I do have many contract with different recurrence date.

Cheers
Babatoko

**Comment by flotho** [comment]
Hi @babatoko ,

didi you have a look to https://github.com/OCA/contract/issues/504
