### ISSUE TITLE
[12.0] error in migration from 11.0

### ISSUE THREAD

**Issue by sergiocorato** [OCA/contract#492]
This function https://github.com/OCA/contract/blob/14e46b14006ba9391c9f7ccff5d0aa9794eb68e0/product_contract/migrations/12.0.3.0.0/pre-migration.py#L6 generate an error when upgrading from 11.0 because in pre-migration the field is not yet created.

```
2020-03-23 17:45:00,070 12921 ERROR pretecno odoo.sql_db: bad query:             UPDATE product_template
            SET recurring_invoicing_type = 'post-paid'
            WHERE recurring_rule_type = 'monthlylastday'
        
ERROR: ERRORE:  la colonna "recurring_rule_type" non esiste
LINE 3:             WHERE recurring_rule_type = 'monthlylastday'
```

**Comment by pedrobaeza** [comment]
I have migrated from 11.0 without problem. Do you have latest code in 11.0?

**Comment by sergiocorato** [comment]
mm, yes, I pull every time

**Comment by pedrobaeza** [comment]
Well, as said, I haven't found this problem, but I haven't checked code.

**Comment by sbejaoui** [comment]
This migration was for 12.0.2.0.0 to 12.0.3.0.0 to introduce the monthly last day prepaid option but apparently we forget about v 11.0 where the field wasn't there.

You can add a check on the version like here 

https://github.com/OCA/contract/blob/14e46b14006ba9391c9f7ccff5d0aa9794eb68e0/contract/migrations/12.0.4.0.0/post-migration.py#L57-L60

**Comment by sergiocorato** [comment]
So the migration has to be done only if version is == '12.0.2.0.0' I understand, I propose a PR

**Comment by pedrobaeza** [comment]
Closing this as PR is merged.
