### ISSUE TITLE
[12.0][BUG] agreement_legal: error upgrading (stage_type)

### ISSUE THREAD

**Issue by ygol** [OCA/contract#501]
It might be #355 that add a stage_type but without updating existing data.

> 2020-04-17 09:04:11,553 7 ERROR ygol-stag-apr14-1034772 odoo.sql_db: bad query: ALTER TABLE "agreement_stage" ALTER COLUMN "stage_type" SET NOT NULL
> ERROR: column "stage_type" contains null values
> ****

**Comment by ygol** [comment]
Here's what I did to circumvent the problem until fixed:

1. Temporarily disable the "required" flag at https://github.com/OCA/contract/blob/6b7576f37f06ee6ddc571b9e40f97b5f0f177b0e/agreement_legal/models/agreement_stage.py#L29

2. Upgrade the module (agreement_legal).

3. Undo hack from point 1

Hope this helps

**Comment by max3903** [comment]
@murtuzasaleh Log your time on task 19158
