### ISSUE TITLE
[12][Question] Configuring product_contract correctly

### ISSUE THREAD

**Issue by svalaeys** [OCA/contract#504]
Hi,

This is a question about a typical configuration for the product_contract module. If this is not the right place for such a question, please let me know the alternatives.

I have been playing around with product_contract because I have a client who fits the mold perfectly: the company sells all kind of building data captors (heat sensors, water consumption sensors, etc) and, in the same offer, a subscription to have the data from these captors analysed.

My confusion is about contract_template_id on a contract product. I have tried two different things:
- I tried adding lines to this contract template. When I add a line to the sale.order pointing to the product linked to the template, and I confirm the sale order, the resulting contract has two lines: one generated from the sale order, and one generated from copying the template. This seems to suggest lines to be added to the template need to be additional lines that wouldn't be in the offer, whatever they may be.
- I tried not adding any lines to the template. As expected, things just work fine. But if it's the base case, I am struggling to understand why the contract_template_id is then mandatory since it really does not seem to bring much (the price list, journal and the contract type is not "nothing", but I hope you get my point). 

I am worried that I am missing the point. The goal of contract_template_id could also be simply to give the ability to create two different contracts from the same sale_order, since sale order lines are filtered by contract ids.

Anyway, instead of assuming wrongly, I thought I'd ask. Thank you for your assistance.

**Comment by sbejaoui** [comment]
Hi, 

I understand that this field confusing you. It wasn't clear for me neither when I first started using the `product_contract` module. 

This field came form an old version of the module where contract product was used simply to duplicate the contract template in a new contract without any impact from the SO.

Now, it permit a salesperson to make in a one quote for contractual and non-contractual products and then transform it to one or multiple contracts.  

So now, the `contract_template_id` field have two major use-cases:

1. Define additional contract lines which must be added to the customer contract but are not included in the sales order lines. For example, some companies automatically add annual contract management fees that are not included in the quote.
2. Group contract line per contract template (two products with two different contract templates will conclude a contract  each)

This field must not be required in the product template model (we didn't find the time yet to do it), and the grouping process at sale order confirmation must consider it.
- continue grouping contract line with the same contract template
- group all contract line without a contract template in one contract

Regards

**Comment by svalaeys** [comment]
Thank you very much for this clear explanation. I try to see what happens if the contract_template_id is left empty and if it's all good, I will do the pull request. Thanks again,

Stephane
