### ISSUE TITLE
[Question] Contract Invoice Offset

### ISSUE THREAD

**Issue by miscs** [OCA/contract#515]
Hi all,

I know this is not the best place for questions but I searched and tried a lot and am still struggling how to use contracts for my use-case. I think I would need an "invoice offset" which I can modify, but let me describe my scenario first:

- I sell subscriptions which should be invoiced pre-paid 1 year directly on contract sign
- the contract runs until notice is received from the customer
- the following invoices should be invoiced 4 weeks before the next period

Somehow I am not able to create such a contract:
- I cant use invoice offset, since it is read only and set to 0
- I can´t move the date of the next invoice to a date 4 weeks earlier after the first invoice is generated, because of error message "You can't have the next invoice date before the date of last invoice for the contract line ..."

I read that Invoice Offset is read-only because of backwards-compatibility. So no chance to use this?

Any pointers are highly appreciated. Sorry if I am missing something obvious! 

Thanks
Steve

PS.: Is there an advantage to using auto-reneval instead of just leaving the end date blank?

**Comment by pedrobaeza** [comment]
@sbejaoui can you answer this?

**Comment by sbidoul** [comment]
@miscs  Making the invoice offset user modifiable would be a good improvement and code has been prepared for that change, IIRC. Someone has to think through the implication in terms of compatibility, and the impact on related modules that create contracts, from e.g. sales orders. But it is certainly feasible and would add even more flexibility to the module.

**Comment by miscs** [comment]
Hi @sbidoul Thanks for your answer. If we leave default at "0" only invoice creation should be effected or am I missing something?
To address our current need I added two new dates-field to the contract which I use for "subscription-period start / end". The original fields "Date Start" / "Next period start" are set to 6 weeks prior our new subscription-period fields. This way the invoice is send 6 weeks in advance and we can show subscription period on invoices etc.
Works but is of course a little error prone...
