### ISSUE TITLE
error at select money

### ISSUE THREAD

**Issue by patsotoe** [OCA/contract#516]
Im using odoo 12 and when the invoice is generated, the value of the contract its not converted at the main currency.

**Comment by pedrobaeza** [comment]
The currency is taken from the billing journal, so select another one with the desired currency.

**Comment by patsotoe** [comment]
The money of billing journal is in clp AND in the product of the contract is usd, when i create the invoice the value of this Is in usd a not in CLP. Any idea of how Solve this?

**Comment by pedrobaeza** [comment]
There's no support for that automatic conversion. You should input the price in CLP as fixed price.
