### ISSUE TITLE
[12.0] [BUG] Contract lines not importing the Renew Every and Termination Notice Before field from the Contract Template

### ISSUE THREAD

**Issue by GleydsonHudson** [OCA/contract#518]
I have created a contract template with and set the fields below
<br>
![Contract Template](https://user-images.githubusercontent.com/21695360/82348217-d86a3680-99f8-11ea-9ebe-018a02c83054.PNG)
<br>
However, when I create a new contract and ask for that contract template, the fields above are not imported, as you can see in the image below.
<br>
![Contract Line](https://user-images.githubusercontent.com/21695360/82348710-8675e080-99f9-11ea-860b-7044c7b69b87.PNG)
<br>
Any suggestions or solutions for this issue?

<br><br>
Thanks,
Gleydson Silva

**Comment by JordiADARIA** [comment]
your right, ive checked it on Runbot and its happening the same. I think the purpose of select a template its only to get some kind of "header" data from the contract template.. but it will be better to import also the details on lines, ill try to find where it is..
