### ISSUE TITLE
Error contract_sale_invoicing

### ISSUE THREAD

**Issue by OpencloudPro** [OCA/contract#524]
Module: contract_sale_invoicing
File: contract_sale_invoicing/models/contract.py line 19

you cannot call it with self because the decorator is multi. We need a for on the self before. 

Thanks.

**Comment by iw3hxn** [comment]
Yes same error, when create invoice get:

"Expected singleton: contract.contract(8, 14, 7, 26, 27, 32, 4, 29, 28, 34, 5, 12, 16, 18, 35, 33, 31, 24, 17, 23, 30, 20, 21, 22, 9, 13, 15, 6, 10, 25, 19, 11)"


I fix change line 19
if not self.invoicing_sales
to
if list(set(self.mapped('invoicing_sales'))) == [False]:

**Comment by enricostano** [comment]
Could be related to https://github.com/OCA/contract/pull/437

**Comment by enricostano** [comment]
Or this... https://github.com/OCA/contract/pull/505

**Comment by iw3hxn** [comment]
yes, 505.
Error is on cronjob

the decorator is multi so need to use mapped inside

**Comment by pedrobaeza** [comment]
Fixed in #537
