### ISSUE TITLE
I found a strange behavour:

### ISSUE THREAD

**Issue by devCbssolutionsRo** [OCA/contract#532]
I found a strange behavour:
When you create contract with parner1 (without generating bills), then duplicate the contract and change partner to parner2 and you generate bills, this bills show parner1 instead of partner2.

EDIT: I think a solution (it works for me), is an onchange on partner_id to change also invoice_partner_id, then the bills will be partner2 instead of partner1.

_Originally posted by @novis82 in https://github.com/OCA/contract/pull/446#issuecomment-650185726_

looks that he code is doing this.
what is wrong?

    @api.onchange('partner_id')
    def _onchange_partner_id(self):
        self.pricelist_id = self.partner_id.property_product_pricelist.id
        self.fiscal_position_id = self.partner_id.property_account_position_id
        if self.contract_type == 'purchase':
            self.payment_term_id = \
                self.partner_id.property_supplier_payment_term_id
        else:
            self.payment_term_id = \
                self.partner_id.property_payment_term_id
        self.invoice_partner_id = self.partner_id.address_get(['invoice'])[
            'invoice'
        ]

**Comment by pedrobaeza** [comment]
Please create a PR with your proposed solution

**Comment by pedrobaeza** [comment]
Closing waiting for the PR.
