### ISSUE TITLE
[RFC] agreement_serviceprofile - Can't use product variants

### ISSUE THREAD

**Issue by patrickrwilson** [OCA/contract#546]
Currently the service profiles have a product_id field referencing the product.template model. Because of this, you can't select a product variant for the service profile product. This is a limiting factor for the service profile product selection, especially when the other modules (Like sales) typically reference product.product.

I'm proposing changing the product_id field to reference product.product instead.

**Comment by patrickrwilson** [comment]
Ping @max3903 @osi-scampbell

**Comment by max3903** [comment]
ping @dreispt @kvedder-amplex @ygol

**Comment by ygol** [comment]
make sense to me.

**Comment by osi-scampbell** [comment]
@patrickrwilson @max3903 @ygol How about a m2o field to product.product as well as a boolean in the settings to determine which to use? This way current users can continue as per usual and still have access to this functionality if they so choose.

**Comment by patrickrwilson** [comment]
@osi-scampbell I'm fine with that too, that way both can be supported. We would prefer the original product.template field hidden and just use the product.product field.
