### ISSUE TITLE
[12.0] #END# usage in section and notes

### ISSUE THREAD

**Issue by levkar** [OCA/contract#549]
If you put #END# in a note or a section line, you get the following error on invoice creation:

  File "/opt/odoo/addons/contract/models/contract_line.py", line 747, in _insert_markers
    name = name.replace('#END#', last_date_invoiced.strftime(date_format))
AttributeError: 'bool' object has no attribute 'strftime'

**Comment by nikul-serpentcs** [comment]
@levkar please add reproduce steps

**Comment by pedrobaeza** [comment]
I have the steps clear, but I don't get the purpose: do you try to get that mask replaced by any kind of date? Which date?

**Comment by levkar** [comment]
Purpose is to write the invoicing period on a line at the very top/bottom of the invoice instead of putting it on each line's description.

**Comment by pedrobaeza** [comment]
That's not possible, as each line can have its own period. We can fix for not having error, but you can't use that markers in sections with that purpose.

**Comment by levkar** [comment]
I created this issue to get the error fixed, not to request this as a feature. Yet, it would be good feature if they (especially notes) might act like a product in terms of dates (since sections and notes are lines too).

**Comment by pedrobaeza** [comment]
Notes will work that way if you configure so.

**Comment by levkar** [comment]
Yes, if the error is fixed...

**Comment by pedrobaeza** [comment]
AFAIK, there's no error in notes when you configure then to be shown with previous/following line

**Comment by levkar** [comment]
Yes it works! I tried with custom. Should i close this issue or keep it open?

**Comment by pedrobaeza** [comment]
I will fix the error, so let's keep it opened.

**Comment by filipocc** [comment]
> Yes it works! I tried with custom. Should i close this issue or keep it open?

Hi @levkar , could you please explain how did you fix it? I'm facing the same issue with brand new contracts (due to there is no last_date_invoiced date.)

**Comment by filipocc** [comment]
> I will fix the error, so let's keep it opened.

Hi @pedrobaeza , any updates on this?

**Comment by pedrobaeza** [comment]
I have been thinking that this is not something to solve, as you can't use such markers in a note that is not invoiced with previous/next line. A possible fix is to not error, but let the markers, and then other people will put an issue saying that "markers are not converted", so it will be the same. Then:

- Don't use markers in notes.
- Use it, but putting the invoicing mode as specified.
