### ISSUE TITLE
[RFC] contract_auto: Automatic Payment

### ISSUE THREAD

**Issue by lasley** [OCA/contract#55]
This module will provide the ability to accept automatic payments on contracts. It is a continuation of the discussion [here](https://github.com/OCA/contract/issues/45#issuecomment-286616680). 

I was originally trying to abstract this to work directly on invoices, but I cannot think of a good way to do that while still maintaining a streamlined workflow. As such, this RFC is limited in scope to contracts only (unless someone has a brilliant idea).

It will add a m2o on `account.analytic.account` to relate to a `payment.token` that should be used for automatic payment. The `payment.token` will be domain restricted to children of the `partner_id` of the `account.analytic.account`.

If a `payment.token` is defined on the `account.analytic.account`, the invoice will be validated immediately after creation. A payment will then be generated using the v10 [server2server interface](https://github.com/odoo/odoo/blob/10.0/addons/payment/models/payment_acquirer.py#L587) against the `payment.token` that is defined.

It will also add an m2o on `account.analytic.account` to relate to a `mail.template`. If a template is defined, it will be emailed to the customer automatically when the invoice is validated.

It will also add an option at the contract and contract template level to require the use of automatic payment on the contract. If this option is selected, a `payment.token` will be required for the contract.

Sounds simple enough I think. Anyone have any ideas of how to abstract this beyond contracts, or some existing code I can base on?

**Comment by lasley** [comment]
Can a PSC please tag as `question` and `10.0` milestone? Thanks!

**Comment by vonpupp** [comment]
I would like to help with this, if possible.

I successfully developed a payment-gateway (PagSeguro) integration module however I am still learning Odoo development. What do you guys think/propose?

**Comment by lasley** [comment]
@vonpupp - This feature should be independent of the payment gateway. Assuming that PagSeguro has a concept of payment tokens, we should be good to go. 

I believe we've started dev on this, I'll let @bmw95 comment on progress (LABS-411)

**Comment by vonpupp** [comment]
Thank you @lasley. Is this dev open/available? Is there any way to collaborate or be able to check how things are going and follow the code/progress? I would like to help.

**Comment by lasley** [comment]
@vonpupp - The ticket only moved to in progress a few days ago, so I'm not sure if there is anything of substance yet (and there's not a branch linked to our internal ticket at the moment). We always develop in the open though, so that answer is most certainly a yes. 

Realistically now that we've started dev, I expect the feature to be PR ready in a week or so. @bmw95 is the one working that one and will need to follow up with additional specifics next time he's in.

**Comment by lasley** [comment]
@vonpupp - turns out we hadn't gotten far. I took this one over and made a rough outline of it [here](https://github.com/LasLabs/contract/tree/release/10.0/LABS-411-contract_auto/contract_auto). Will tag you in the PR when ready

**Comment by vonpupp** [comment]
Great @lasley, thank you very much! I just tried subscriptions using stripe python's lib (without Odoo) and it is very easy to use. I will have a look on your skeleton code and see if I can figure something out. My goal would be to be able to process recurrent payments (via Stripe/Credit cards, Paypal and PagSeguro).

**Comment by lasley** [comment]
As long as the payment acquirer is compatible with the [server to server API](https://github.com/odoo/odoo/blob/10.0/addons/payment/models/payment_acquirer.py#L587), my code should work everywhere

**Comment by vonpupp** [comment]
I have seen that the `payment_stripe` has some s2s methods. I will have to dig into that since I haven't used s2s yet. I will install your module to test it out and try to learn more about s2s.

**Comment by vonpupp** [comment]
@lasley, Could you please enable the issues tab on your fork? I had an issue but I think it is better to keep the conversation over there.

**Comment by lasley** [comment]
@vonpupp - created #67, we can just discuss there.

I'm going to close this RFC now that there's a PR
