### ISSUE TITLE
[13.0][BUG] Contract: Recurring at line level. Different start dates

### ISSUE THREAD

**Issue by misern2** [OCA/contract#565]
Testing the new module on V13 I found out the following bug.

1) Create a simple contract with the Recurrence at line level set to True
2) Create two contract lines with diferent start dates.
Current behaviour:
  Raise an exception on creating the record: date constranints

Expected behaviour:
 Create the record and allow to generate the invoices.

![contract_13_bug](https://user-images.githubusercontent.com/10547008/97187199-847f2d00-17a2-11eb-852d-d7e8358f43f5.png)

On V.12 Works OK!.

**Comment by pedrobaeza** [comment]
But according the screenshot, the date of next invoice is correct. Maybe it's because you have created both at the same time with no saving in between and it's a framework problem?

**Comment by misern2** [comment]
I tested both ways.
First creating all lines at once, then creating one by one and the same error appears.
All the info in the form seems correct.

**Comment by pedrobaeza** [comment]
Is this reproducible in a unit test? If so, please pass me for debugging.

**Comment by misern2** [comment]
Just creating a simple contract with the two lines, raise the exception:

[Code Example](https://github.com/QubiQ/contract/commit/ffc1e3d61bd39dad1d4c3c143a08240a0fff86f3)

**Comment by pedrobaeza** [comment]
Why are you putting this `date_start` at header level:

https://github.com/QubiQ/contract/commit/ffc1e3d61bd39dad1d4c3c143a08240a0fff86f3#diff-da995126f9f1cfc9e7074016896e39baf645c3c59d1e5364bdb098a4fb7248a9R170

**Comment by misern2** [comment]
ups!. It was a copy paste. Anyway without this line we get the same error.

**Comment by pedrobaeza** [comment]
OK, I will check
