### ISSUE TITLE
[13.0][BUG] Contract: Not recurring at line level. Different last invoice dates

### ISSUE THREAD

**Issue by hgarridoco** [OCA/contract#570]
Hi,

If I try to generate a contract with recurrence at the header level and generate a start date set in the previous moment and the next recurring date for this month, it generates the next invoice date wrong.

That screenshots are from rubot:

Before generate invoice:
![image](https://user-images.githubusercontent.com/16115608/97976651-3e8e1e80-1dcb-11eb-99f5-92b4e9e9d737.png)

After generate invoice:
![image](https://user-images.githubusercontent.com/16115608/97976682-48b01d00-1dcb-11eb-8107-3a78f796abea.png)

**Comment by pedrobaeza** [comment]
Unless you give more information on how to reproduce the problem and which is the problem, nothing can be done.

**Comment by hgarridoco** [comment]
> Unless you give more information on how to reproduce the problem and which is the problem, nothing can be done.

Sorry, I press enter so quickly.

I filled it properly.

**Comment by pedrobaeza** [comment]
I don't see the exact sequence for the data entering. Can you record a video?

**Comment by hgarridoco** [comment]
You can check it at this video: 

https://www.loom.com/share/fa3ccee03b194190a28b4f4527019df7
