### ISSUE TITLE
[14.0] contract: Missing required account on accountable invoice line.

### ISSUE THREAD

**Issue by rizzopablo** [OCA/contract#572]
Hi there! I'm testing contract on v14, after modifying the company assignment to use the new call "self.partner_id.with_company(self.company_id.id)", I'm facing this issue trying to create an invoice from contract:

> 2020-11-04 18:38:32,031 215522 ERROR multinaltu_v14 odoo.sql_db: bad query: INSERT INTO "account_move_line" ("id", "create_uid", "create_date", "write_uid", "write_date", "account_id", "amount_currency", "analytic_account_id", "blocked", "company_currency_id", "company_id", "contract_line_id", "credit", "currency_id", "date", "date_maturity", "debit", "discount", "display_type", "exclude_from_invoice_tab", "is_rounding_line", "move_id", "move_name", "name", "partner_id", "price_subtotal", "price_total", "price_unit", "product_id", "product_uom_id", "quantity", "sequence", "tax_base_amount", "tax_exigible", "tax_line_id", "tax_repartition_line_id") VALUES (nextval('account_move_line_id_seq'), 2, (now() at time zone 'UTC'), 2, (now() at time zone 'UTC'), NULL, '0.00', NULL, false, 19, 2, 1, '0.00', 19, '2020-11-04', NULL, '0.00', '0.00', NULL, false, false, 14, 'MISC/2020/11/0001', 'Hosting Profesional Anual (pablorizzo.com)', 20, '0.00', '0.00', '49.00', 1, 1, '1.00', 10, '0.00', true, NULL, NULL) RETURNING id
ERROR: new row for relation "account_move_line" violates check constraint "account_move_line_check_accountable_required_fields"
DETAIL:  Failing row contains (15, 14, MISC/2020/11/0001, 2020-11-04, null, null, null, 2, 19, null, null, 10, Hosting Profesional Anual (pablorizzo.com), 1.00, 49.00, 0.00, 0.00, 0.00, null, 0.00, 0.00, 0.00, null, f, null, 19, 20, 1, 1, null, null, null, null, null, null, 0.00, t, null, null, null, null, null, null, null, null, f, f, 2, 2020-11-04 18:38:31.431819, 2, 2020-11-04 18:38:31.431819, 1, null). 
2020-11-04 18:38:32,032 215522 WARNING multinaltu_v14 odoo.http: Missing required account on accountable invoice line. 

But I don't get to understand where should I set the missing account.

I can create an invoice for the same client, same product, if I do it directly in Invoicing/Customers/Invoices

**Comment by pedrobaeza** [comment]
The module is not yet migrated to v14, so it's normal that errors arise. Closing as not applicable.
