### ISSUE TITLE
[12.0][BUG] Contract documents not available for portal users

### ISSUE THREAD

**Issue by mgielissen** [OCA/contract#595]
The new portal function for contracts doesn't show up for portal users under /my/home (only for backend users with admin rights)?

**Comment by victoralmau** [comment]
Please explain all steps to reproduce bug and version (12.0 or 13.0).

It's important to clarify that in /**my/home** only appear "_Contracts_" if user have some contract. 
Maybe need to add follower user in contract.

**Comment by mgielissen** [comment]
> Maybe need to add follower user in contract.

Adding the user as follower solves it indeed.

**Comment by pedrobaeza** [comment]
From README:
![Selección_004](https://user-images.githubusercontent.com/7165771/103294037-55c74200-49f1-11eb-9a0b-2922cd5ff624.png)
