### ISSUE TITLE
Access contract.line.wizard

### ISSUE THREAD

**Issue by frantischek** [OCA/contract#599]
Hi,
when I try to start a new recurring contract I get this message (sorry for german):

> You are not allowed to access 'Assistent für Vertragspositionen' (contract.line.wizard) records.

In debug mode clicking on the invoice creation button also shows a error message: 
> Fehlender erforderlicher Account in der Rechnungszeile
(something like: missing account in invoice)

Method name: recurring_create_invoice

Can someone help me please. 
Thanks.
BR
Frantischek

**Comment by flotho** [comment]
please indicate which release
