### ISSUE TITLE
redundant field view 

### ISSUE THREAD

**Issue by nabilragab** [OCA/contract#608]
Dont need to extend the suppliers form view with an additional field.

It already inherits and displays. remove redundant      on line 42

**Comment by pedrobaeza** [comment]
Please add more details about what are you talking about

**Comment by nabilragab** [comment]
contract_payment_mode\views\contract_view.xml


contract_contract_supplier_form_view 
This record is redundant, it only causes a duplicate payment mode field to display in the form for supplier contract.

**Comment by pedrobaeza** [comment]
Please add a PR doing such removal.

**Comment by nabilragab** [comment]
I Don't have write access...

**Comment by pedrobaeza** [comment]
That's why I am talking about a PR (pull request).

**Comment by pasgou** [comment]
To complete : the field is duplicate AND the domain is inbound where it should be outbound.

**Comment by flotho** [comment]
maybe https://github.com/OCA/contract/pull/528

**Comment by flotho** [comment]
ping @pedrobaeza I thinks that issue is fiexed by my PR, could we close this one as @nabilragab don't answer.

Regards
