### ISSUE TITLE
Accessing Templates from Dashboard

### ISSUE THREAD

**Issue by toddrabs** [OCA/contract#615]
I've added new templates under Configuration -> templates. However, when I go to the dashboard I can't find a way to pull up a template on that screen. Is there a way to do this that I am missing? Maybe this is an enhancement, in which case if there is anyone that can help I'd love to chat more on this. Thanks!

**Comment by newtratip** [comment]
I'm not found select template on agreement under dashboard and operation too.

**Comment by newtratip** [comment]
I add `Create Agreement From Template` under operation menu https://github.com/OCA/contract/pull/647, Is this ok for you ?

**Comment by toddrabs** [comment]
This is great, thank you!
