### ISSUE TITLE
[12.0][QUESTION] How can I sell a monthly contract over e-commerce using the recurring product?

### ISSUE THREAD

**Issue by eduaparicio** [OCA/contract#617]
**How can I sell a monthly contract over e-commerce using the recurring product?**

Whenever I try to do so, it results in: 
- contract with no end date, despite the contract template configured to bill monthly and renew automatically after 1 year;
- contract lines duplicated

The same behaviour occurs when I validate a Quotation containing the recurring product.
Important to mention that the Contract Template also contains the recurring product.

Let me bring a little context...

Before creating this issue, I have compared 2 different instancies of Odoo 12 CE. The first, that **works fine**, is **not updated since June 2020**.
The second one received the latest updates (as of today: contract [12.0.8.3.1], product_contract [12.0.5.1.2]). This is the instance duplicating lines of the recurring product in the invoice. 

I assume I am doing something wrong here. Could anyone help?

Thanks in advance!
Best!
Eduardo.

**Comment by flotho** [comment]
Hi,

I'll share with you how we handled this in our Odoo v12.
First we developped a module that allow to use order templates without having full eshop : https://apps.odoo.com/apps/modules/12.0/website_sale_template/
Then in this quotation template I added a line with a product for hosting :
![image](https://user-images.githubusercontent.com/1043935/146257350-b7b85ed3-642c-443b-a0c1-5054584ed11e.png)

![image](https://user-images.githubusercontent.com/1043935/146257422-b3a0b651-4d1f-418e-b942-1561a924f115.png)

![image](https://user-images.githubusercontent.com/1043935/146257486-92015bb7-3d19-4f4a-b4ed-a15761faa8e2.png)

Hope this answer to your question.

Regards
