### ISSUE TITLE
Contrat not generated automatically 

### ISSUE THREAD

**Issue by cremain** [OCA/contract#638]
Hello all

I use this module and createt a daily recurring invoice on prepaid mode. So the different invoices not created automatically every day.

How can i resolve this issue ?

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem with exact data an Odoo version?

**Comment by cremain** [comment]
Odoo Version: 13 community

Steps:
1. Create a contrat
2. define the recurrency by Daily

Result: No contrat generated automatically.
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/47972090/108587172-127eb500-734a-11eb-8552-a7a398de46f1.png">

**Comment by cremain** [comment]
Hello

I just upgraded the module and it's worked now.

Thanks

**Comment by opensourcer-2021** [comment]
Hello
i'm using odoo 12 ce , and i m actually trying to understand contract and agreement addons for reccurent service , reccurent invoicing ,  and recurrind payment ( i can share the requested workflow for an eventual contribution) but i have some problems :
1- i cannont find "Generate recurring invoices automatically" and when i do the contract , contract is generated then it' doesnt create the invoice automatically , i changed the action from 1 day to 1 minute but nothing changes , i upgraded the module but same , in debug mode i can create invoice manually
2- i installed also  contract_invoice_auto_validate but where to put values "[queue_job] channels=root:5,root.CONTRACT_INVOICE:1" as requested : https://odoo-community.org/shop/product/contract-invoice-auto-validate-5663?search=auto+validate#attr=8945 , is it a screenshot share please?
3- i installed "contract_invoice_start_end_dates" and "account_invoice_start_end_dates" , start and end dates appears only in view invoicing lines and not in report invoicing lines so customer cannot undestand wich period he's going to pay or already paid
best regards
