### ISSUE TITLE
Post automatically created invoices by the cron

### ISSUE THREAD

**Issue by cremain** [OCA/contract#639]
Dear all

I use the module to manage recurrency invoices. Congratulations and thanks for this great module.

So i have some questions:
1. How to post automatically the invoices created by the cron?
2. Is it possible to have the contract_id on the invoice? If yes, how? My need is to display the frequency and  type on the invoice.

Odoo version: 13 community
Contract version;: 13.0.2.3.5

**Comment by pedrobaeza** [comment]
1. There's no such mechanism yet implemented.
2. You have the contract line at invoice line level, so adding a computed field for that in your custom layer is simple.

Closing as no issue, but questions.
