### ISSUE TITLE
[RFC] contract_cancel: Cancel Contract With Lapsed Invoices

### ISSUE THREAD

**Issue by lasley** [OCA/contract#64]
This will be a fairly simple module that will automatically cancel any contract that has an invoice in `Past Due` status, instead of creating a new invoice. It will provide this option at the contract and contract template level in order to allow for customization where needed.

It will hook into the pre-existing [`account.analytic.account.recurring_create_invoice`](https://github.com/OCA/contract/blob/10.0/contract/models/account_analytic_account.py#L167), and will first evaluate whether there are any past due invoices related to the contract. If there are, the `recurring_invoices` option will be deselected thus cancelling the contract. The super will not be called in this instance.

Simple enough I think, although I'm not sure if I'm going about the whole cancelling of the contract correctly. I think deactivating it is not what we're going for either though?

Let me know if you know of a pre-existing module/strategy for this that I'm overlooking, or if I'm going about this incorrectly.

**Comment by pedrobaeza** [comment]
Any news with this?

**Comment by lasley** [comment]
Nope. We haven't actually had this happen in production yet, so I guess it's not as big of an issue as I was expecting - at least for my uses - guess people don't want their websites shut off.

Admittedly I can't find an internal ticket for this, so it seems I completely spaced actually throwing it on the roadmap 😆 . I went ahead and did that now - it's probably worth keeping the RFC open.

**Comment by pedrobaeza** [comment]
OK, let's keep it
