### ISSUE TITLE
Question for agreement type and agreement subtype

### ISSUE THREAD

**Issue by newtratip** [OCA/contract#645]
On the agreement, it has 3 types (module `agreement_legal`)
- Agreement
- Contract
- Letter of Intent 

and in each agreement types, it has setting a subtype.

![Selection_196](https://user-images.githubusercontent.com/24691983/109464737-b9292b00-7a99-11eb-85cc-4998c11f37c0.png)

**My question**
1. What is difference `Agreement` and `Contract` type ?
2. What is agreement subtype ? and real case how can I apply ?

@ygol, Could you help for more explain this ?

Thanks in advance.

**Comment by ygol** [comment]
Our use case for agreements is the management of frame contracts with partners. 
Legally defining prices, quantities, and terms of conducting business. 

* The agreement type simply permits the categorization. 
  I further use a custom module that forces the naming of an agreement based on the agreement type.  So in your example, any agreement of type "agreement" would automatically start with "AG-" and "contract" with "CO-" and "letter of intent" with "LI-". This thus gives an immediate visual clue about the agreement. 

* I do not use the subtype.

Do not hesitate to further ask precisions here or on discord.

**Comment by newtratip** [comment]
@ygol, Thanks for your answer. I more understand :)

I'm a beginner on an agreement module. May I ask another question ?

> I try to play this module following steps.
> 1. Setting stage
> 2. Setting agreement types
> 3. Create agreement template
> 4. Create agreement by click `New Agreement` on template
> 5. Fill in some data on the agreement

Is this step correct ?

If this step is correct, agreement is created from template menu only which permission with `Manager` group.

For the `user` group, I can't create agreement from template.

Could you suggest me for this ?

**Comment by ygol** [comment]
Hi
```If this step is correct, agreement is created from template menu only which permission with Manager group.
For the user group, I can't create agreement from template.
```

This is not correct. an agreement **user** can access templates and create agreements.

**Comment by newtratip** [comment]
Hello @ygol,

I create one user with access right `Agreement User`
![Selection_209](https://user-images.githubusercontent.com/24691983/110267999-829c6480-7ff3-11eb-961a-9aa63d19714f.png)

I'm not see any templates, I have access with menu Dashboard, Operations, Master Data
![Selection_213](https://user-images.githubusercontent.com/24691983/110271261-36a0ee00-7ffa-11eb-819a-acfd4096f7a0.png)

Am I doing somthing wrong ?

**Note** I add `Create Agreement From Template` https://github.com/OCA/contract/pull/647, I'm not sure this is way a correct.

**Comment by ygol** [comment]
![image](https://user-images.githubusercontent.com/2945174/110289099-9cd54300-7ff1-11eb-8540-59faa642fc8a.png)

you could also edit the action for the Operation/agreements view and remove the domain
