### ISSUE TITLE
[12.0] Contract Smartbutton not filter by partner_id, is showing all contracts.

### ISSUE THREAD

**Issue by JorgeQuinteros** [OCA/contract#648]
Tested in runbot: When click in contract smarbutton is not filtering by the user active.
![contract_smartbutton_show_all_contracts](https://user-images.githubusercontent.com/43784849/109779179-f9a5b780-7c05-11eb-8066-b14bb59b6304.gif)

**Comment by newtratip** [comment]
Fixed in https://github.com/OCA/contract/pull/642
