### ISSUE TITLE
VAT not appear on contract edition 

### ISSUE THREAD

**Issue by cremain** [OCA/contract#660]
Dear all

On contract edition, VAT not appear in product including line.

**Comment by pedrobaeza** [comment]
Sorry, I don't get the problem

**Comment by cremain** [comment]
To edit a recurring contract, there is no possibility to include VAT for a product.

**Comment by cremain** [comment]
To edit a contract, there is no possibility to include VAT for a product.

**Comment by pedrobaeza** [comment]
You mean taxes, and of course that's not possible, as that is got from product and fiscal position.
