### ISSUE TITLE
Prepaid contract, invoices not generated in accordance of recurring period

### ISSUE THREAD

**Issue by cremain** [OCA/contract#665]
Hello team

I use odoo community v13 to have recurring invoices. 
On recurring period, I selected weekly and invoice type, I selected prepaid 

So, invoices didn't generated in accordance of my configuration, prepaid mode as one week before the invoice date.

How to resolve this issue?

**Comment by pedrobaeza** [comment]
Pre-paid means that the paid interval is from the invoice date to the end of such interval, not one week before.
