### ISSUE TITLE
[Question] [contract_mandate]: Is it same as SEPA?

### ISSUE THREAD

**Issue by ygol** [OCA/contract#673]
Hi,

Is the module contract_mandate compatible with SEPA mandates? 
Is there a difference?

Use case targeted is to have an invoice generated from a contract to automatically charge de customer using the SEPA mandate - payment mean - pre-established for that customer.

thank you

**Comment by pedrobaeza** [comment]
The module is for indicating at contract level which mandate to use for the generated invoices. Nothing more and nothing less.
