### ISSUE TITLE
Issue on Agreement legal module after install on V13 community

### ISSUE THREAD

**Issue by laumar92** [OCA/contract#676]
After correct installation, i got this error message when trying to create new template or agreement

Retraçage   :
--
Error: def is not defined
_render@https://xxxxx.xxx/web/content/748-4c00473/web.assets_backend.js:3948:1'
start/<@https://xxxxxxx.xxx/web/content/748-4c00473/web.assets_backend.js:821:1408

Thks for help on this
Rgrds,
LM

**Comment by pedrobaeza** [comment]
Is this reproducible on OCA runbot?

**Comment by laumar92** [comment]
Yes same issue on OCA Runbot

Traceback:
Error: def is not defined
_render@http://3483635-13-0-2cb67a.runbot2-3.odoo-community.org/web/content/742-fef1869/web.assets_backend.js:3587:1
start/<@http://3483635-13-0-2cb67a.runbot2-3.odoo-community.org/web/content/742-fef1869/web.assets_backend.js:821:1408
Thks
LM

**Comment by agharaafat** [comment]
i have the same issue with the same message 
Odoo 13 EE

**Comment by FedericoGregori** [comment]
Same error fresh install Odoo 13 CE

**Comment by mvcastellano** [comment]
same issue

**Comment by dolphine-ke** [comment]
The issue is still on Odoo 13 CE
