### ISSUE TITLE
Sales Order to Agreement - Section lines are messing up with agreement lines

### ISSUE THREAD

**Issue by 5B-MAVERICKS** [OCA/contract#687]
Agreement_sale_legal installed (v14)

I'm creating a sales order w/ agreement template.
Sales order lines contain products + section lines.

When confirming the sales order, 'agreement app' is generating an agreement and I get the following error:
"Agreement line - Unit of measure..."

It means that it tries to turn the "section" line from the Sales Order into an agreement line.
but because not a classic Sales order, plenty of information are missing including UoM.

**Comment by vix-db** [comment]
Same problem here.

INSERT INTO "agreement_line" ("id", "create_uid", "create_date", "write_uid", "write_date", "agreement_id", "**name**", "product_id", "qty", "sale_line_id", "**uom_id**") VALUES (nextval('agreement_line_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 2, '**SECTION LABEL**', NULL, 0.0, 30, **NULL**) RETURNING id

**ERROR: null value in column "uom_id" violates not-null constraint**

DETAIL:  Failing row contains (1, null, **SECTION LABEL**, 2, 0, null, 1, 2022-05-03 09:29:48.93576, 1, 2022-05-03 09:29:48.93576, 30).
