### ISSUE TITLE
Can not generate invoices on contract when setting discount

### ISSUE THREAD

**Issue by trixocom** [OCA/contract#698]
This is the error:

Cannot create unbalanced journal entry. Ids: [47]
Differences debit - credit: [-396.69]

$396,69 is the amount of the discount.
Odoo 13 ce latest build.

**Comment by pedrobaeza** [comment]
Please try to reproduce the problem in standard OCA runbot (https://runbot.odoo-community.org/runbot/110/13.0), and explain the complete detailed steps to get to it.
