### ISSUE TITLE
Cannot see contract at portal in odoo 13

### ISSUE THREAD

**Issue by santyabreu** [OCA/contract#708]
Hello everyone, and thank you for your support

After installing the module, I generate a customer contract, but I can't see it in the portal. I have done the step of putting the contact as a follower but I can't get it to appear . Have I forgotten to do something?

Best Regards
Santy

**Comment by pedrobaeza** [comment]
Unless you reproduce the problem in the OCA runbot to be analyzed, nothing can be done here.

**Comment by santyabreu** [comment]
deleted screenshots

**Comment by santyabreu** [comment]
Runbot http://3498561-13-0-bc4017.runbot2-3.odoo-community.org/

**Comment by pedrobaeza** [comment]
Everything is working fine in runbot:

http://3498561-13-0-bc4017.runbot2-3.odoo-community.org/web#id=1&action=402&model=contract.contract&view_type=form&cids=&menu_id=133

http://3498561-13-0-bc4017.runbot2-3.odoo-community.org/my/contracts

Closing meanwhile no further evidence is presented.

**Comment by santyabreu** [comment]
Good morning Pedro

I think you have misunderstood the message I have given. 

I am not saying in any way that the module is doing an improper operation or that it is incorrectly installed. Like you, I consider that it is working correctly. I have opened the ticket because I have not been able to get the contracts to appear in the customer portal.
I think it's more of an operational issue, rather than a technical glitch.

Would you be so kind as to help me get the contracts to appear in the customer portal? 
I've followed the steps in the forum (put the contact on follow-up, as shown in the screenshots I've posted), but I still can't get it to work. Can you help me with this?

Best Regards,
Santy

**Comment by pedrobaeza** [comment]
This issue tracker is only for technical problems, not functional ones.

**Comment by santyabreu** [comment]
Ok, thank you. I will unninstall this module, due to the poor documentation and not visible functionality. I was even willing to pay for help to get this module up and running with the functionality it promises, but looking at the responses.... I will find another solution. I have seen members of this git who have helped with functionality, but I see that this is not the case.
Very Kind
Bye.
