### ISSUE TITLE
next_period_date_start computation problem

### ISSUE THREAD

**Issue by AdamBark** [OCA/contract#711]
The if statement [here](https://github.com/OCA/contract/blob/6c6601e6a5dec16273de7ba957ff1b3fa74e863c/contract/models/contract_recurrency_mixin.py#L115) sets next_period_start_date to False which then breaks that statement with the following error:
`TypeError: '>' not supported between instances of 'bool' and 'datetime.date'`

**Comment by pedrobaeza** [comment]
Steps to reproduce the problem.

**Comment by AdamBark** [comment]
> Steps to reproduce the problem.

- Create a contract
- Select "recurrence at line level"
- Make a new line
- Turn on autorenewal
- Select a start date other than the default

**Comment by AdamBark** [comment]
Nothing has changed to fix this as far as I can tell
