### ISSUE TITLE
Contract problems 

### ISSUE THREAD

**Issue by opensourcer-2021** [OCA/contract#748]
Hello
i'm using odoo 12 ce , and i m actually trying to understand contract and agreement addons for reccurent service , reccurent invoicing , and recurrind payment ( i can share the requested workflow for an eventual contribution) but i have some problems :
1- i cannont find "Generate recurring invoices automatically" and when i do the contract , contract is generated then it' doesnt create the invoice automatically , i changed the action from 1 day to 1 minute but nothing changes , i upgraded the module but same , in debug mode i can create invoice manually
2- i installed also contract_invoice_auto_validate but where to put values "[queue_job] channels=root:5,root.CONTRACT_INVOICE:1" as requested : https://odoo-community.org/shop/product/contract-invoice-auto-validate-5663?search=auto+validate#attr=8945 , is it a screenshot share please?
3- i installed "contract_invoice_start_end_dates" and "account_invoice_start_end_dates" , start and end dates appears only in view invoicing lines and not in report invoicing lines so customer cannot undestand wich period he's going to pay or already paid
best regards

**Comment by flotho** [comment]
Hi,

So many things to answer in this thread.

> Hello i'm using odoo 12 ce , and i m actually trying to understand contract and agreement addons for reccurent service , reccurent invoicing , and recurrind payment ( i can share the requested workflow for an eventual contribution) but i have some problems : 
> 1- i cannont find "Generate recurring invoices automatically" and when i do the contract , contract is generated then it' doesnt create the invoice automatically , i changed the action from 1 day to 1 minute but nothing changes , i upgraded the module but same , in debug mode i can create invoice manually 

> 2- i installed also contract_invoice_auto_validate but where to put values "[queue_job] channels=root:5,root.CONTRACT_INVOICE:1" as requested : https://odoo-community.org/shop/product/contract-invoice-auto-validate-5663?search=auto+validate#attr=8945 , is it a screenshot share please? 

Please provide your conf to check if the queue job is correctly set as explained there https://github.com/OCA/queue/tree/14.0/queue_job#id4
Please provide the content on the execution message of a job that failed

> 3- i installed "contract_invoice_start_end_dates" and "account_invoice_start_end_dates" , start and end dates appears only in view invoicing lines and not in report invoicing lines so customer cannot undestand wich period he's going to pay or already paid best regards
Please open a separate thread with module name so that maintainer will be able to be addressed properly.
