### ISSUE TITLE
bug Contract , product contract , website product contract , order product contract

### ISSUE THREAD

**Issue by opensourcer-2021** [OCA/contract#749]
hello 
i'm using odoo 12 ce , 
i create contract product , then i create a contract model using that contract product : 
i cannot choose the duration in the contract product  : example 1, or 3 or 6 months or ...years, but i can choose it in contract model  in my case i choosen 24 months
Variables (qty , duration , invoicing....discount ) doesent change when i change in any side , example if i change qty in contract model  it doesnt change in contract product ---> normally if i choose to use contract model from contract product it sync date from it and vice versa .
Now i try to create an order from sale module : i choose to sell a contract product , here it's getting the price directly from contract model , if for example i choose % discount (in my case 5% discount)  it comes with discounted price directly from contract model ,  normaly it's coming with all details price , qty , and discount to the oderline view .
Nom i try to publish on website , the contract product appears like normal product with only qty = 1 , normaly my qty is 24 so that the amount will be 24x product price for all the duration , and normaly must create the contract also normaly it creates the first invoice but it doesn't.
best regards

**Comment by flotho** [comment]
Does this #617 could answer some of your questions.

Additionally please provides a runbot url for testing and/or screenshot, it will help people to identify what could probably be wrong.

Regards
