### ISSUE TITLE
RFC: Add a wizard to create invoices in batch (calling the function `cron_recurring_create_invoice`)"

### ISSUE THREAD

**Issue by jcdrubay** [OCA/contract#782]
**Is your feature request related to a problem?**

When a batch creation of Invoices by scheduler fails, Accountants are "blind" and have no way to try running a batch create again (unless they are also Technical Users).

**Describe the solution you'd like**

Add a wizard to create invoices in batch (calling the function `cron_recurring_create_invoice`)" so a Billing Manager could call the function that creates invoices in batch without the need of asking for help from the technical team.

In case of exception, raise a `UserError(_("The contract with name %(name)s fails to generate invoice. Try from the contract for more details.", ("name": rec.name))`.

**Describe alternatives you've considered**

Try creating invoices contract by contract to find which one causes an issue being very careful not to invoice a contract twice.

**Comment by pedrobaeza** [comment]
AFAIK, you already have such option, in a menu entry called "Invoice manually xxxx contracts" on each Customers and Vendors top menus.

**Comment by jcdrubay** [comment]
Ok, but that means going on each customer one by one ... in many cases, this is the same as running the create invoice Contract by contract.

**Comment by pedrobaeza** [comment]
No, that wizard makes it for all pending contracts to that introduced date...

**Comment by jcdrubay** [comment]
Thanks for pointing this out @pedrobaeza 

And what do you think about the part that would raise UserError pointing to the contract?

Something like this:

```python
def _recurring_create_invoice(self, date_ref=False, disable_raise=True):
        try:
            invoices_values = self._prepare_recurring_invoices_values(date_ref)
            moves = self.env["account.move"].create(invoices_values)
            self._invoice_followers(moves)
            self._compute_recurring_next_date()
            return moves
        except Exception as e:
            import logging
            msg = "Retrying for contract: %s", rec
            logging.error("Exception in _recurring_create_invoice: %s", e)
            for rec in self:
                logging.info(msg)
                try:
                    rec._recurring_create_invoice(date_ref=date_ref, disable_raise=False)
                except Exception as e:
                     raise UserEror(_("The contract with name %(name)s fails to generate invoice. Try from the contract for more details.", ("name": rec.name)))
            raise  # We should always raise because the list of invoice is expected in
            # return
```

**Comment by pedrobaeza** [comment]
Please don't mix topics. I close this one.
