### ISSUE TITLE
Contract template is useless because it creates empty invoices

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/contract#80]
I have tried to use contract templates in my own instalation of odoo 10 and in oca runbot and that is what happens:

- I create a contract template with a product

- I use this contract template in a contract

- the resulting invoice is empty with no product

You can add the product directly to the contract and it works, but if you use the template , then the invoice is empty.

**Comment by pedrobaeza** [comment]
@lasley can you check?

**Comment by lasley** [comment]
Hah we can see where my functional testing ended here (sorry, I suck). It seems the templated invoice lines are present on the contract up until the point you hit save, which causes them to vanish.
