### ISSUE TITLE
Why cancel button is not available for some contract lines?

### ISSUE THREAD

**Issue by eruiz67** [OCA/contract#848]
I use the contract.contract module. I want to know in witchscenarios
the cancel button of a line is available? Because some times I want to cancel a line and the
## Module
contract.contract

## Describe the bug
I want to know what condictions must be present in order to see the cancel button of contract line available. Is there any way cancel a line that is in the state "Close"?

**Additional context**
I am working with odoo v12

**Comment by rousseldenis** [comment]
Indeed, an explanation should be an improvement on conditions to have some actions possible (in interface) as it's in code but not really clear, even when debugging.
