### ISSUE TITLE
[RFC] Contract Sales

### ISSUE THREAD

**Issue by angelmoya** [OCA/contract#85]
On maintenance contract it's usual to have this cases:
- periodicicaly invoices (done with contract module)
- periodicicaly tasks, and task can consume materials, and invoice can depends on task and materials

If contract generate sales, we can define diferent products for tasks and materials, and create task for project, and stock picking for materials, this way sale order could be like "work order".

Other thing that I need is to have is recurring interval by product, not global.

I just start to work on a module called contract_sale to do this things.

**Comment by pedrobaeza** [comment]
You already have project_task_material/project_task_material_stock for consuming products and sale_service_project for generating task from Sales Orders. What does this module add?

**Comment by angelmoya** [comment]
Create recurring sale orders from contract, instead of create invoices

**Comment by angelmoya** [comment]
project_task_material is right, but I prefer to create sale order because this way I can create a picking and invoice delivery qty

**Comment by pedrobaeza** [comment]
project_task_material_stock create stock moves, but you're right that the track is not the same as with sales order.

The module should be called contract_sale_generation for being more explicit, as you can have also sales orders that generates contracts.

**Comment by angelmoya** [comment]
OK, nice.

I started to do it keeping it simple.

I create a type field on contract that could be sale or invoice, and contract generate sale or invoice.

Next steeps:
- Define recurring periods on lines, I think this functionality could be nice on contract module
- Define type on lines

**Comment by pedrobaeza** [comment]
For several periods, you can define several contracts and use the module https://github.com/OCA/contract/tree/9.0/contract_invoice_merge_by_partner. Any way, it can be one possibility for keeping all in one document, but you will complicate a lot the logic.

Several types (sales order/invoice) by line is also to complicate too much I think.

**Comment by angelmoya** [comment]
WIP on #87

**Comment by pedrobaeza** [comment]
Closing as there's a PR.
