### ISSUE TITLE
[15.0] Contract template is not called

### ISSUE THREAD

**Issue by gregory-moka** [OCA/contract#856]
## Module
Recurring - Contracts Management

## Describe the bug
1- Create a new Contract template, save it
2- Create a contract, try to call the contract template : nothing happen

## To Reproduce
**Affected versions**: 15.0

1. Go to Invoicing > Setting > Contracts > Contract template
2. Create a new template, save it
3. Create a new contract, try to call the Contract template

**Expected behavior**
As axpected, the template should be called on the actual contract

**Additional context**
Ex on runboat : http://oca-contract-15-0-dd11b2afb13b.runboat.odoo-community.org/web#id=1&cids=1&menu_id=114&action=281&model=contract.template&view_type=form

![image](https://user-images.githubusercontent.com/45974412/179250499-f2d36150-48cc-46c4-959a-5a9ee5f0bb4e.png)

**Comment by ygol** [comment]
@gregory-moka the template is called when saving. the lines are added accordingly. pls check again

**Comment by gregory-moka** [comment]
🤔 mhh.. ok
Then, the behaviour is weird, cause, once the contract is saved, the contract lines are activated. To be complient with the quotation template behavious, the content of the contract should come with the selection, then, we can remove non needed lines, and at the end, save and activate the contract.
If you save the contract with non-needed lines, then, you have to cancell those lines, and only after, remove them.
