### ISSUE TITLE
Contract > UOM not used to compute the unit price

### ISSUE THREAD

**Issue by gregory-moka** [OCA/contract#879]
## Module
`contract`

## Describe the bug
It seems that the contract does not correctly compute the sutotal if we use the UOM.

## To Reproduce
**12.0, 13.0, 14,0 & 15,0**:
 
- Create a UOM with a random ratio (Unit & Dozen for example)
- Use this UOM on contract
- See the unit price is not changed

**Expected behavior**
As we have on sale order, the unit price has to be changed on UOM change.

**Additional context**

**Comment by flotho** [comment]
Any feedback on this one @gregory-moka  ?
