### ISSUE TITLE
Limited by time contracts

### ISSUE THREAD

**Issue by xavierjimenez** [OCA/contract#89]
In Odoo 8.0, you can select a defined amount of time on the contract, limiting the hours you can work on the project associated with the contract. Also, there's a computed field that shows the remaining time you have left.

Here's a screenshot of what I'm talking about:
![renewal_contract](https://user-images.githubusercontent.com/22770010/29507099-f97e50c4-864e-11e7-8e4b-301179d55637.jpeg)

I haven't seen a way to do that with the OCA module, is it possible or it's pending to be done? I could try to work on it if no one's doing it.

**Comment by pedrobaeza** [comment]
This is not something planned right now, as now you do that with sales orders. That's why this other RF was  created: https://github.com/OCA/contract/issues/85. Check it to see if it fits.

**Comment by xavierjimenez** [comment]
Great, thanks I'll check it out!
