### ISSUE TITLE
15.0 or above : Any way to link task with contract and use worklog to calculate how many time is remaining

### ISSUE THREAD

**Issue by yboujraf** [OCA/contract#904]
Dear,

I 'd like to : 

1. link tasks to a contract with work log
2. calculate how many time is remaining in a pre-paid contract following the work log consumed
3. trigger if not enough service , an event like email and flag to inform overdue time
4. order extra service to the existing contract
5. report all the tasks done for a contract and show the pre-pai and already used

Best Regards,

**Comment by rousseldenis** [comment]
@yboujraf I think there is analytic account on a project. Why not using both to track consumption ?

**Comment by yboujraf** [comment]
Dear @rousseldenis 

I am based in Brussels.
We are not using analytic account as per a company with two engineers.

I am using : 

- Jira and Jira Service Desk cloud (need to copy all the issue and worklog to odoo manually)
- Odoo V8
- Contract module from camptocamp but not more supported to the latest odoo version. It was nice because can set TimeSheet, Task, ...

![image](https://user-images.githubusercontent.com/6151258/207894156-07548e38-7837-4123-82d4-17f669068a50.png)


Migration : 

- to migrate from odoo 8.0 to v14.0 or 15.0 
- to install module in oca/contract and agreement for v14.0, I see the migration to v15.0 is under process.
- to install module in oca/connector-jira for v15.0 but it seems no success at this stage (already pushed some issues)

But if could propose a solution will be great.

BR
Youssef

**Comment by yboujraf** [comment]
Finally, I found the way.

### product

- Product Type : Service
- Invoicing Policy : Based on Timesheets
- Unit of Measure : Days instead of units. 1 days = 8 Hours as per the UoM conversion.

![image](https://github.com/OCA/contract/assets/6151258/85de318a-f41a-451c-9e4f-1200f9a8c4c2)

- Create on Order : Project & Task but not mandatory

![image](https://github.com/OCA/contract/assets/6151258/c368402b-ff4a-4bb2-be86-ff3f1c0894c5)

Then I add my timesheet as it is

![image](https://github.com/OCA/contract/assets/6151258/85dad40e-ab80-4287-9c25-ef99459118ab)

Then I can see in my SO the number of days delivered 

![image](https://github.com/OCA/contract/assets/6151258/944c1427-a64c-4511-8d85-f9d3ef6bc970)

Next step, is to 'create invoice' and automatically, Odoo will invoice the 16 days of services already done.

BR
