### ISSUE TITLE
[12.0] You can't have a date of next invoice anterior to the start of the contract line XX on pre-paid contract

### ISSUE THREAD

**Issue by maisim** [OCA/contract#911]
It is not possible to create an invoice prior to the start of the service (contract line) even if this one is set as pre-paid

## Module
contract

## Describe the bug
It is not possible to create an invoice prior to the start of the service (contract line) even if this one is set as pre-paid
On contract save an exception is thrown, becaus of this constraint:
https://github.com/OCA/contract/blob/373affd2e5ff74214584d888a5e62b3f674cb9b9/contract/models/contract_line.py#L579-L590

## To Reproduce
**Affected versions**: 12.0.8.6.0

1. Create a contract
2. Add a line wich start in future
3. Set the next invoice date prior to the start of the line "start"
4. Save and close the line
4. Save the contract

**Expected behavior**
We should be able to set the invoice date before the start of the service (on pre-paid contract)

**Comment by Ismaw34** [comment]
On a 14 upgraded from 13 also happens.

**Comment by maisim** [comment]
@Ismaw34 
~~Strange because it works here~~ (14.0 runbot)
http://oca-contract-14-0-cab52350c3a3.runboat.odoo-community.org/web#id=5&action=413&model=contract.contract&view_type=form&cids=&menu_id=316

Probably because of this :
https://github.com/OCA/contract/blob/cab52350c3a3e1ee3619a33f0761819244934b22/contract/models/contract_line.py#L466-L467

Edit: I just try again on this link, I'm not able to save the contract if the invoice date < contract start date.
So same as on 12.0

**Comment by maisim** [comment]
https://github.com/OCA/contract/compare/12.0...maisim:contract:12.0

For 12.0, this do the trick

I will  PR soon

**Comment by rafaelbn** [comment]
Hello @maisim ! I confirm this BUG in 12, 13 and 14

Did you made the PR? Before it, It would help really to check and review

- https://github.com/OCA/contract/pull/841
- https://github.com/OCA/contract/pull/852
- https://github.com/OCA/contract/pull/853
- https://github.com/OCA/contract/pull/854
- https://github.com/OCA/contract/pull/893
- https://github.com/OCA/contract/pull/899

**Comment by maisim** [comment]
Hi @rafaelbn,
> Did you made the PR? Before it, It would help really to check and review

Not for the moment, I just did a quick fix, but I did not check for potential side effects

I also found others problem like bad computation of periods end (on montly, quarterly types) ... Thanks for the references I will look at it on the next week

**Comment by Ismaw34** [comment]
> @Ismaw34 ~Strange because it works here~ (14.0 runbot) http://oca-contract-14-0-cab52350c3a3.runboat.odoo-community.org/web#id=5&action=413&model=contract.contract&view_type=form&cids=&menu_id=316
> 
> Probably because of this :
> 
> https://github.com/OCA/contract/blob/cab52350c3a3e1ee3619a33f0761819244934b22/contract/models/contract_line.py#L466-L467
> 
> Edit: I just try again on this link, I'm not able to save the contract if the invoice date < contract start date. So same as on 12.0

The issue happens here:
https://github.com/OCA/contract/blob/cab52350c3a3e1ee3619a33f0761819244934b22/contract/models/contract_line.py#L501
The contract says for example, last date 03/31/2022 and next invoice 04/01/2022, says cant have the next invoice before the date of last invoice.
Thats weird because the next invoice is after the last date invoiced but still says is not.
