### ISSUE TITLE
[contract] Stability between versions

### ISSUE THREAD

**Issue by rafaelbn** [OCA/contract#916]
Hello @OCA/project-service-maintainers ,

After 2 years out of this repo I'm back and I can see diferences between version around FIX and IMP

This mean the product is different.

I see FIX in 13 that are not in 14 and 15
I see IMP in 14 that are not ir 13 and 15
I see 12 is outdated with everything in general.

Furthermore the module is not really user friendly and obvious features that should be in the module and outside in separate modules like https://github.com/OCA/contract/tree/14.0/contract_update_last_date_invoiced

It is just my fault or do you agree here?

Is there any way for a funcional to check differences between versions?

If we make PR to make all homogenous are you going to validate them or just block them?

I don't know the feeling but after 8 years in the past using the module today I realize that contract module is unintelligible for newbies.

Maybe I'm wrong, this is just my feeling.

Thank you for your feedback.

Best regards

**Comment by leemannd** [comment]
Hello @rafaelbn welcome back.
I haven't been working much on this repository until a few month ago. So I don't know its history.

> Is there any way for a funcional to check differences between versions?

Such checks and forward ports of fixes can be done using https://github.com/OCA/oca-port .

> If we make PR to make all homogenous are you going to validate them or just block them?

I don't want to block any improvement, but `all homogeneous` is a bit vague.
