### ISSUE TITLE
[14.0][15.0] Incorrect selection of Payment Mode from the Partner data

### ISSUE THREAD

**Issue by douglascstd** [OCA/contract#923]
The automatic selection of the Payment Mode when the Partner is selected in the Supplier Contract is wrong Payment Mode (inbound), the correct one would be outbound Payment Mode.

## Module
[contract_payment_mode](https://github.com/OCA/contract/tree/14.0/contract_payment_mode)

## To Reproduce
**Affected versions**:

1. Create a Supplier Contract
2. Select the Supplier "Deco"
3. The Payment Mode broght into the contract will be an **Inbound** Payment Mode selected on the partner data.

14.0 version
![image](https://user-images.githubusercontent.com/20867090/216049686-5da56195-8aab-4223-a6b1-f0a48a0d490e.png)
15.0 version:
![image](https://user-images.githubusercontent.com/20867090/216050480-6f2b81cb-9cea-4794-bfd0-0a4863c513df.png)
16.0 version:
There isn't the contract app in this version yet.

Expected information on the partner data
![image](https://user-images.githubusercontent.com/20867090/216049787-297547c7-08c2-4add-a3aa-4d8454287187.png)

Demonstration Video:
https://user-images.githubusercontent.com/20867090/216049926-86119c73-684f-47ab-9ae5-bc8cea3a60d7.mp4

**Expected behavior**
The Outbound Payment Mode seleted on the partner must be brought into the supplier contract

@marcelsavegnago @augustodinizl

**Comment by pedrobaeza** [comment]
This was fixed for v14 in #909 

The fix is pending to be ported to v15. Please do it.

**Comment by pedrobaeza** [comment]
Oh, it was ported in #910

**Comment by douglascstd** [comment]
> Oh, it was ported in #910

Hi Pedro Baeza, thank you for your quick answer. I know the PRs #910 and #909, that I've submited my approval on that.

I guess, I wasn't clear on my Issue...

The Issue is not on the domain on selection field "Payment Mode", but when the partner is select, and the defaulft values from the partner shoud be broght do fullfill some field in the contract form. The field "Payment Mode" is fullfill with the INBOUND Payment mode insted the correct OUTBOUND Payment Mode.

We can see this behavor on the video:  https://user-images.githubusercontent.com/20867090/216049926-86119c73-684f-47ab-9ae5-bc8cea3a60d7.mp4

**Comment by douglascstd** [comment]
To ilustrate the issue: 
![image](https://user-images.githubusercontent.com/20867090/216057733-63f536a1-be73-4c62-9a4e-c69ebe105648.png)

@pedrobaeza with this explanation, could issue be reopened?

**Comment by marcelsavegnago** [comment]
@douglascstd I understand what you're presenting. In fact, the previous PRs only resolve the domain in the selection and do not deal with anything in relation to the standard payment method. I understand how valid it is to keep the issue open.

**Comment by pedrobaeza** [comment]
Understood. This line should be specialized according contract type:

https://github.com/OCA/contract/blob/d20f48d2b2c36030d290476ffee3e8ed9772b6e0/contract_payment_mode/models/contract.py#L16
