### ISSUE TITLE
[15.0] You can't have the end date before the date of last invoice for the contract line

### ISSUE THREAD

**Issue by Entrepreneur-AJ** [OCA/contract#956]
## Module
contract

## Describe the bug
when trying to stop a contract line in odoo 15.0 I get the following error:
You can't have the end date before the date of last invoice for the contract line 'product name'

## To Reproduce
**Affected versions**: 15.0

1. Create new customer contract with multiple products with recurrance at line level selected.
2. Try to stop a line in the contract
3. Receive error message.

**Expected behavior**
Line should show as stopped and not be included on next invoice.

**Additional context**
OS: Fedora 36
Python Version:  3.10.11
Odoo Version: 15

**Comment by iTecan** [comment]
Hello,

this error you are indicating is not a bug as such, it is correct that you cannot finalise a contract at a date prior to an invoice already issued.
