### ISSUE TITLE
The form to create manually the invoices, is too slow, almost half a minute for every invoice generation

### ISSUE THREAD

**Issue by cstevanatonehos** [OCA/contract#986]
## Module
contract

## Describe the bug
As the title say, I am experiencing a really slow invoice generation, it takes almost 30 seconds to create just an invoice.
After some debugging I found that these lines cause a lot of the waiting time
https://github.com/OCA/contract/blob/14.0/contract/models/contract.py#L436-L440

## To Reproduce
**Affected versions**:
14.0

1. Create an invoice (or many) manually from the wizard

**Expected behavior**
A faster method, I expect it to take at most 1/2 seconds per invoice

**Comment by pedrobaeza** [comment]
This is done to ensure that all the fields, even those coming from other modules, are filled on invoice generation. You can develop another alternative method and propose it as an extra module, hooking on this one.

Closing as no issue, but a balance between features and cons.
